### ISSUE TITLE
Orchestrator: Use show slaves command for discovery

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#103]
Orchestrator documentation recommends setting this option to false. However, I found that with mysql-operator setups, discovery only works with this command. The other option (discovery by IP address), does not work.

**Comment by AMecea** [comment]
Please let me know what is your case in which orchestrator doesn't discover new nodes. I know there is a bug and should be fixed. The controller tries to discover nodes in [SyncOrchestratorStatus](https://github.com/presslabs/mysql-operator/blob/master/pkg/mysqlcluster/orc_reconciliation.go#L39) but only the first time.

**Comment by smanpathak** [comment]
@AMecea as mentioned, I have observed this issue with mysql clusters newly created with the operator. This may not be related to existing clusters when operator restarts/upgrades.

**Comment by smanpathak** [comment]
FWIW, I found that deploying v0.1.12 of images results in this behavior. The latest images work fine.
