### ISSUE TITLE
Feature Request: Support emptyDir option

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#114]
I am working on an on-prem deployment with mysql-operator. For baremetal deployments, storage can come from

1. A storage provider from commercial storage vendor.
2. Host local volumes/NFS
3. Host directory.

I am hoping that the final deployment is as simple as possible, without overly relying on quality of external storage provider. With 1 and 2, I faced issues.

1. For external storage providers (at least the ones I worked on), the K8s integration is not that great. These providers don't scale well and make the deployment unstable. 
2. The local volume provider: (https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume/provisioner) suffers from issues: (a) It does not clean up properly, so if a new statefulset re-uses a deleted volume, it sometimes gets unclean state from previous DB (b) If a node dies, the replica is lost because volume claim is specific to the lost node. 

Given these issues, can we support emptyDir as option for volumes? If the user knows what they are doing and make sure sufficient replicas are always available, all the shortcomings above can be overcome.
Happy to work on it, if this makes sense.

**Comment by calind** [comment]
Yup, sounds reasonable. Can you do a spec proposal?

**Comment by calind** [comment]
So here my initial attempt at this:

```go
// VolumeSpec is the desired spec for storing mysql data
type VolumeSpec struct {
	// EmptyDir to use if no PersistentVolumeClaim or HostPath is specified
	// +optional
	EmptyDir *corev1.EmptyDirVolumeSource `json:"emptyDir,omitempty"`
	// HostPath to use instead of a PersistentVolumeClaim.
	// +optional
	HostPath *corev1.HostPathVolumeSource `json:"hostPath,omitempty"`
	// PersistentVolumeClaim to use. It has the highest level of precedence,
	// followed by HostPath and EmptyDir
	// +optional
	PersistentVolumeClaim *corev1.PersistentVolumeClaimSpec `json:"persistentVolumeClaim,omitempty"`
}
```

We should also note that the volume spec should be initially immutable, since volume definitions for StatefulSets are immutable as well.

**Comment by Fgruntjes** [comment]
Would also love this feature, any news on this?

**Comment by calind** [comment]
We will keep the current `VolumeSpec` inlined but deprecated, and move forward with the proposed change. We will drop the inlined PVC spec once we bump the resource version. The migration should be done without any user intervention.
