### ISSUE TITLE
Cron job definition | unexpected backup schedule

### ISSUE THREAD

**Issue by HBO2** [presslabs/mysql-operator#138]
@calind &  @AMecea I have set the backupSchedule to "1 14 * * *" but noticed the backup is running every 2 hours (1 minute past every 2 hours. My intention is to run it at 1 minutes past 14:00 hours. 
I confirmed my format of Cron on several sites. So, I am bit confused. Could one of you help me?

thx

**Comment by AMecea** [comment]
Hmm, we use this cron library: https://godoc.org/github.com/robfig/cron  (and the schedule is 6 fields format) and it's different than usual crontab format with 5 fields. I think we should document this, or to chose another cron library that uses the right cron format. This has bitten me before, too.

This is the meaning of the cron format:

Field name   | Mandatory? | Allowed values  | Allowed special characters
----------   | ---------- | --------------  | --------------------------
Seconds      | Yes        | 0-59            | * / , -
Minutes      | Yes        | 0-59            | * / , -
Hours        | Yes        | 0-23            | * / , -
Day of month | Yes        | 1-31            | * / , - ?
Month        | Yes        | 1-12 or JAN-DEC | * / , -
Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?

**Comment by HBO2** [comment]
@AMecea Great. So, at least no need to doubt my understanding of cron :-)  
From my point no need to use other library, Just a comment and example in the deployment.yaml. 
 thx!

**Comment by bluven** [comment]
@AMecea I think you used this library: [github.com/wgliang/cron](https://github.com/robfig/cron) which is forked from [https://github.com/robfig/cron](https://github.com/robfig/cron).
 
I'll update your documents and examples,  hope you will like it.
