### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#15]
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

When a pod is shut down gracefully it should:
1. set to maintenance in orchestrator
2. if it's master, then the operator should do a graceful failover if there are other slaves

**Comment by calind** [comment]
We need a resolution on kubernetes/kubernetes#73584 before proceeding.

**Comment by afirth** [comment]
This would be super helpful, but I'm pretty confident that pod finalizers won't work (the container will die before finalizers are executed). I think the container needs to trap SIGTERM on pid 1, or use prestop hooks. Would you be able to explain the issue you faced with prestop? Would be great to see this feature in, might solve the majority of #107 causes too.

**Comment by cndoit18** [comment]
I think this is done
cc @calind
