### ISSUE TITLE
Rclone executable is missing

### ISSUE THREAD

**Issue by HBO2** [presslabs/mysql-operator#162]
After upgrading the cluster to 0.2 operator the already existing backup job ito the working s3 url  is failing with following error:
 
`ERROR	sidecar	mysql-operator-sidecar/main.go:112	take backup command failed	{"error": "rclone start error: exec: \"rclone\": executable file not found in $PATH"}`

**Comment by AMecea** [comment]
Thanks, @HBO2, I found the issue, it's because of the rewrite of the docker file. We missed installing `rclone` command. I republish the image with `rclone` inside, to fix the issue for now.

**Comment by AMecea** [comment]
@HBO2 I've fixed the issue when you reported it, but because of #165 it didn't work. Now should work. Also, I will release the operator version `0.2.1` today which includes all fixes.
