### ISSUE TITLE
Error connecting to master | cluster name longer than few chars

### ISSUE THREAD

**Issue by HBO2** [presslabs/mysql-operator#170]
@AMecea 
I tested the new release and in essence everything is going ok. Also upgrading existing operator with cluster (only one replica, because of the old issue)
On dev K8s cluster . created also a total fresh and new operator with a new cluster (1 master and 2 slaves) from k8s perpective they seems healthy, but the orchestrator and the log show otherwise -> replication simply wont start after imported a copy of existing database. The error message is:

```
2018-11-29T07:32:11.464493Z 0 [Note] InnoDB: Buffer pool(s) load completed at 181129  7:32:11
2018-11-29T07:32:11.482593Z 11 [ERROR] Slave I/O for channel '': error connecting to master 'repl_1FULi@prod-ain-cluster-mysql-0.prod-ain-cluster-mysql-nodes.defaul:3306' - retry-time: 10  retries: 1, Error_code: 2005
```

Earlier in the log I see a warning:

```
2018-11-29T07:32:10.849587Z 8 [Warning] Neither --relay-log nor --relay-log-index were used; so replication may break when this MySQL server acts as a slave and has his hostname changed!! Please use '--relay-log=prod-ain-cluster-mysql-1-relay-bin' to avoid this problem.
```

Please find belwo  the full log of one of the slaves:
[logs-from-mysql-in-prod-ain-cluster-mysql-2.txt](https://github.com/presslabs/mysql-operator/files/2628083/logs-from-mysql-in-prod-ain-cluster-mysql-2.txt)

helm ls shows this:
`ain-mysql-operator      14              Wed Nov 28 21:57:22 2018        DEPLOYED        mysql-operator-0.2.1    v0.2.1          default`

 To be complete please find below the full log of the orchestrator:

[logs-from-orchestrator-in-ain-mysql-operator-orchestrator-0.txt](https://github.com/presslabs/mysql-operator/files/2628108/logs-from-orchestrator-in-ain-mysql-operator-orchestrator-0.txt)
 
NB: please note  the k8s is running on AKS (azure) 1.11.3

**Comment by AMecea** [comment]
We figure it out that the problem is because of the hostname too long, the hostname is truncated at 63 characters. 
I will check further this issue.
Thanks @HBO2

**Comment by calind** [comment]
There is a limit on the MySQL side to 60 characters for hostnames. https://bugs.mysql.com/bug.php?id=87243

We should look for a workaround for this issue, because this limitation leased room for only 44 characters to (2*cluster_name + workspace).

**Comment by AMecea** [comment]
We add some documentation about this in #215 

There is nothing to do about this, it's a MySQL limitation.
