### ISSUE TITLE
How to use an official Percona or Mariadb image for this operator?

### ISSUE THREAD

**Issue by juexun** [presslabs/mysql-operator#190]
When I used "percona:5.7.24" from official docker hub, I failed  to start the mysql cluster.
The only mysql image is the default image, which is percona@sha256:c8b69b3c753cb04f1cbf8a4a1f295f51675761ee6368a47808a5205e2d45cfeb.

**Comment by delgod** [comment]
Hi juexun,

the latest Percona images don't allow to run processes from root user, in the result, it is needed to add `fsGroup` into StatefulSet options.

**Comment by calind** [comment]
We currnetly use old percona images (with debian). There is #200 for changing to the newer centos ones. As for MariaDB we currently don't plan to add support for it but PR are welcome.

**Comment by AMecea** [comment]
this issue is fixed by #224, now the operator can use all images from Percona
