### ISSUE TITLE
resource limits for main (mysql) container

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#192]
I noticed that the main (mysql) container lacks resource limits. Everything else does have resource limits set.
As a cluster admin, I would like to have resource limits on each container, that way a single container cannot dominate and take away all resources. It also lets me plan better. I set some reasonable limit initially and monitor the applications. If they routinely approach say 90% of limit, I know that I need to bump it up.
Having resource requests satisfies the minimum, which is important as well.
Maybe I am missing something here.

**Comment by smanpathak** [comment]
See a related discussion here: https://github.com/upmc-enterprises/elasticsearch-operator/issues/223

**Comment by delgod** [comment]
Hi @smanpathak,

I believe you just need to specify {{requests}} and {{limits}} in resources section https://github.com/presslabs/mysql-operator/blob/master/examples/example-cluster.yaml#L29

**Comment by smanpathak** [comment]
I tried it, but looks like there's a bug.
My Spec:
```
 podSpec:
     resources:
       requests:
         memory: 1G
         cpu:    200m
       limits:
         memory: 4G
         cpu: 3000m
```

describe po shows following
```
  mysql:
    Container ID:   docker://af40806b26c67f01b75d3ff7279c41717f4197435272b81c2f6297d15cb2ca72
    Image:          percona@sha256:c8b69b3c753cb04f1cbf8a4a1f295f51675761ee6368a47808a5205e2d45cfeb
    Image ID:       docker-pullable://percona@sha256:c8b69b3c753cb04f1cbf8a4a1f295f51675761ee6368a47808a5205e2d45cfeb
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 09 Jan 2019 16:34:01 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     3
      memory:  4G
    Requests:
      cpu:      200m
      memory:   1G
```

**Comment by smanpathak** [comment]
setting cpu as 3G instead of 3000m does the trick.

**Comment by AMecea** [comment]
`3000m` means `3`, so what is reported in description it's ok. Setting `3G` (cpu) will be to much(no limit). See more details [here](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu).

**Comment by smanpathak** [comment]
Thanks!
