### ISSUE TITLE
Cluster is not showing up in orchestrator UI

### ISSUE THREAD

**Issue by tothandras** [presslabs/mysql-operator#194]
Steps to reproduce:

```bash
# install operator
helm init --wait
helm repo add presslabs https://presslabs.github.io/charts
helm install presslabs/mysql-operator --name mysql-operator

# run the example
kubectl apply -f https://raw.githubusercontent.com/presslabs/mysql-operator/master/examples/example-cluster-secret.yaml
kubectl apply -f https://raw.githubusercontent.com/presslabs/mysql-operator/master/examples/example-cluster.yaml

# port-forward orchestrator service
kubectl port-forward service/mysql-operator-orchestrator 8080:80
```

http://localhost:8080/web/clusters/

Environment:

```bash
# Docker for desktop
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"} 
```

Last working chart version is `0.1.14`.

<details>
    <summary>Logs (<code>kubectl logs mysql-operator-66c799d75f-4rwqb</code>):</summary>
<pre>
{"level":"error","ts":1547117609.91812,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_controller.go:218","msg":"failed to update cluster status","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/pkg/controller/orchestrator.(*ReconcileMysqlCluster).Reconcile\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/orchestrator/orchestrator_controller.go:218\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1547117609.9182634,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"controller.orchestrator","Request":"default/my-cluster","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1547117614.905438,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_controller.go:194","msg":"reconciling cluster","cluster":{"metadata":{"name":"my-cluster","namespace":"default","selfLink":"/apis/mysql.presslabs.org/v1alpha1/namespaces/default/mysqlclusters/my-cluster","uid":"14a8b646-14c4-11e9-aa26-025000000001","resourceVersion":"1292","generation":1,"creationTimestamp":"2019-01-10T10:40:00Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"mysql.presslabs.org/v1alpha1\",\"kind\":\"MysqlCluster\",\"metadata\":{\"annotations\":{},\"name\":\"my-cluster\",\"namespace\":\"default\"},\"spec\":{\"replicas\":2,\"secretName\":\"my-secret\"}}\n"},"finalizers":["OrchestratorFinalizer"]},"spec":{"replicas":2,"secretName":"my-secret","podSpec":{"resources":{},"affinity":{}},"volumeSpec":{"resources":{}}},"status":{}}}
{"level":"warn","ts":1547117614.9124258,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:70","msg":"can't get instances from orchestrator","alias":"my-cluster.default","error":"[orc]: status: 500 path: cluster/my-cluster.default msg: 2019-01-10 10:53:34 ERROR Unable to determine cluster name. clusterHint=my-cluster.default, details: <nil>"}
{"level":"info","ts":1547117614.9124966,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:241","msg":"discovering hosts","hosts":[]}
{"level":"info","ts":1547117614.9125304,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:250","msg":"forgeting hosts","hosts":[]}
{"level":"error","ts":1547117614.9177732,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_controller.go:218","msg":"failed to update cluster status","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/pkg/controller/orchestrator.(*ReconcileMysqlCluster).Reconcile\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/orchestrator/orchestrator_controller.go:218\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1547117614.918147,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"controller.orchestrator","Request":"default/my-cluster","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1547117619.9056292,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_controller.go:194","msg":"reconciling cluster","cluster":{"metadata":{"name":"my-cluster","namespace":"default","selfLink":"/apis/mysql.presslabs.org/v1alpha1/namespaces/default/mysqlclusters/my-cluster","uid":"14a8b646-14c4-11e9-aa26-025000000001","resourceVersion":"1292","generation":1,"creationTimestamp":"2019-01-10T10:40:00Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"mysql.presslabs.org/v1alpha1\",\"kind\":\"MysqlCluster\",\"metadata\":{\"annotations\":{},\"name\":\"my-cluster\",\"namespace\":\"default\"},\"spec\":{\"replicas\":2,\"secretName\":\"my-secret\"}}\n"},"finalizers":["OrchestratorFinalizer"]},"spec":{"replicas":2,"secretName":"my-secret","podSpec":{"resources":{},"affinity":{}},"volumeSpec":{"resources":{}}},"status":{}}}
{"level":"warn","ts":1547117619.9116518,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:70","msg":"can't get instances from orchestrator","alias":"my-cluster.default","error":"[orc]: status: 500 path: cluster/my-cluster.default msg: 2019-01-10 10:53:39 ERROR Unable to determine cluster name. clusterHint=my-cluster.default, details: <nil>"}
{"level":"info","ts":1547117619.9117074,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:241","msg":"discovering hosts","hosts":[]}
{"level":"info","ts":1547117619.9117413,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_reconcile.go:250","msg":"forgeting hosts","hosts":[]}
{"level":"error","ts":1547117619.914737,"logger":"controller.orchestrator","caller":"orchestrator/orchestrator_controller.go:218","msg":"failed to update cluster status","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/pkg/controller/orchestrator.(*ReconcileMysqlCluster).Reconcile\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/orchestrator/orchestrator_controller.go:218\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1547117619.9150949,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"controller.orchestrator","Request":"default/my-cluster","error":"the server could not find the requested resource (put mysqlclusters.mysql.presslabs.org my-cluster)","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
</pre>
</details>

**Comment by AMecea** [comment]
Hi @tothandras, please make sure that on k8s (version `v1.10.x`) has   `CustomResourcesSubresources` alpha feature enabled (if using version  `0.2.2`). If you are using version `0.1.x` then this feature should be disabled.

Once subresources are enabled then the status does not get updated and the operator will not notice orchestrator to discover new hosts.

If you have `CustomResourcesSubresources` feature enabled then use the `0.2.2` version of the mysql-operator, which handles ok subresources, else use version `0.1.14` which is the last version that supports k8s < 1.11.

Also if you want to migrate from version `0.1.x` to `0.2.x` then make sure that you follow the steps from [readme](https://github.com/presslabs/mysql-operator#v02x-upgrade).

Hope this helps!

**Comment by AMecea** [comment]
I will close the issue, please reopen if it still happens to you.
