### ISSUE TITLE
Increase volume sizes after disks are full

### ISSUE THREAD

**Issue by kjellberg** [presslabs/mysql-operator#198]
Hello :) 

I've been running this in a staging environment for about a week and it worked perfect (installation via helm as in README.md) until tonight. Now my disk are full and I get the following error in my mySQL pods:

`2019-01-11T10:52:26.446075Z 0 [ERROR] Disk is full writing '/var/lib/mysql/mysql-bin.~rec~' (Errcode: 1618511792 - No space left on device). Waiting for someone to free space...`

I've manually increased the file size for our volumes from 1GB to 5GB, and I've updated the specs for the volumes in k8:

```
"spec": {
    "capacity": {
      "storage": "5Gi"
    },
```

I detached all volumes and attached them again. But I still get the 'Disk is full error' when restarting my pods. 

I can not change PVC's:

```
persistentvolumeclaims "data-cluster1-mysql-1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

What am I missing? How can I help the pods to recognise the new storage space?

Running in a DigitalOcean Kubernetes environment.

Thank you :)

**Comment by AMecea** [comment]
As far as I know, the k8s does not resize automatically PVCs if some [features](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/) are not enabled. Also on DigitalOcean are some people reporting that resizing does not work, see this [issue](https://github.com/digitalocean/csi-digitalocean/issues/106). You can try do it manually as describe in this [article](https://www.digitalocean.com/docs/volumes/how-to/increase-size/).

**Comment by kjellberg** [comment]
Thanks! 

But I tried to delete and recreate the PVC with the same volume name. Volumes got deleted and I lost all data. RIP. Will choose 1000TB volumes next time to stay safe... :P
