### ISSUE TITLE
MySQL cluster has comaster instances when I recreated it.

### ISSUE THREAD

**Issue by juexun** [presslabs/mysql-operator#207]
I deleted the mysql cluster using `kubectl delete -f demo.yaml --cascade=false` and reserved the pvc.
When i recreate the mysql cluster using `kubectl apply -f demo.yaml`
The cluster was in maintenance mode with two co-master instances.
How can I fix it?

**Comment by calind** [comment]
This should be solved by #199.

**Comment by AMecea** [comment]
Also when deleting a cluster with `--cascade=false` the stateful set and pods should not be deleted. Updating controller-util fixes this, this is addressed by #221.

To reproduce this issue, in other words to delete the cluster but don't delete the PVCs, you should delete the cluster with `--cascade=false` and the related objects of the cluster, like stateful set, config maps, etc. Anyway when using cascade deletion you have to be more careful when recreating the cluster.
