### ISSUE TITLE
Do We need an Init pods chown option for root owned volumes ?

### ISSUE THREAD

**Issue by jayunit100** [presslabs/mysql-operator#226]
Hit a little default volume perms issue, related to the 999 user and its abilities to write to a raw volume by default.

Problem:

I have two operator implementations running ~ one is a proprietary vendor, the other is NFS based.  The NFS based pod works fine... But the vendor based pod is not writeable by default via the 999 mysql user.  These are both running on the exact same cluster, same operator version ~ so the only variable is the vendor storage implementation, which i guess publishes volumes which are locked down by default.

Solution?
- Can we run an (optional) init pod with correct /etc/passwd setup, that launches as user 0 as part of the standard deployment, and does a `chown -R mysql...` on the mounted volume?   I think that would fix this issue in general.
- Can we also add CRD documentation for all the knobs to the top level README ? 

Also, another possible improvement to make alongside this : 
- Another thing that is related to this is the ability to select the storageClass in the CRD.  Is there a way to do that?

**Comment by jayunit100** [comment]
(in particular ~ my NFS provisioner 777's the root directory, so its gauranteed to work)... I suppose any vendor storage that *doesn't* do something similar would have a similar issue.  I dont think that there is a standard definition.

That said, if we inject PSP's into the pods for Mysql, I think that the kubelet (since its root) is smart enough then to mount volumes with correct permissions ?  But am not sure.

**Comment by delgod** [comment]
some kubernetes environments don't allow to run containers with root user inside - e.g. openshift.
due to this issue, Percona images don't have root inside, so `chown` command is impossible.

so maybe operator can pass `spec.template.containers[].securityContext.fsGroup` variable as workaround.

**Comment by AMecea** [comment]
Hi @jayunit100, I've already started working on a PR where to set `fsGroup` (as @delgod mentioned) for volumes, to allow using CentOS based images from Percona that runs MySQL with `mysql` user (#224 ). Hope this works with the proprietary vendor storage provider, too.

There is some documentation of basic actions that can be performed on CRDs, you can check on this [getting started](https://github.com/presslabs/mysql-operator/blob/master/docs/_index.md) page.

Also, you can specify the storage class under the `.spec.volumeSpec.persistentVolumeClaim.storageClassName`, more information can be found [here](https://github.com/presslabs/mysql-operator/blob/master/docs/deploy-mysql-cluster.md#cluster-data-volume-configuration).

Hope this helps,

**Comment by jayunit100** [comment]
Awesome ! thanks.

**Comment by AMecea** [comment]
Hi @jayunit100, this issue is fixed by #224, and will be released in version `v0.2.5` of the operator.
