### ISSUE TITLE
recovery docs and implementation code are mis-matched

### ISSUE THREAD

**Issue by hoatle** [presslabs/mysql-operator#234]
https://github.com/presslabs/mysql-operator/blob/master/docs/cluster-recover.md

`initBucketURL` is mentioned from the docs, however, `initBucketURI` is the current working key (following code implementation + examples)

**Comment by AMecea** [comment]
Thank you, @hoatle, for reporting this, I will update the documentation asap. Also, I'm thinking of changing `initBucketURI` into `initBucketURL`, in the future.

**Comment by AMecea** [comment]
@hoatle Would you like to contribute with a PR for this issue? I will be happy to review it and merge it!

**Comment by hoatle** [comment]
@AMecea sure, PR sent https://github.com/presslabs/mysql-operator/pull/242

**Comment by AMecea** [comment]
closed by #242
