### ISSUE TITLE
How to connect to cluster from another Pod?

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#238]
I have a simple Pod to which I am passing in name of the master service of a cluster (and password). However the Pod fails to connect to the cluster. I also kubectl exec-ed inside the Pod and tried to manually connect to cluster, but the connection times out. I have tried using service name of master (my-cluster-mysql-master) as well as just my-cluster-mysql. But with both I am getting connection timeout. What is the correct way to connect to the cluster?

I am following instructions from README and using the helm commands, and hence the chart, listed there.

**Comment by AMecea** [comment]
Hi @devdattakulkarni, The best way to integrate the operator with your application is by using the provided helm [chart](https://github.com/presslabs/mysql-operator/blob/master/docs/integrate-operator.md#using-helm). If you don't want to use it you can inspire from it, for example, see there how we build the [connection URL](https://github.com/presslabs/mysql-operator/blob/924171eee3ae58a04c59f67e2c7f310c4a5f2fd1/hack/charts/mysql-cluster/templates/_helpers.tpl#L35). 

Anyway, your use case should work, you should be able to connect from a pod to the master service as you tried. To debug it I need a little more information. What `kubectl describe svc my-cluster-mysql-master` outputs, does the service has any endpoints? Also, what is the status of the cluster, by running: `kubectl describe mysql my-cluster` if the cluster is not ready or master node is not selected then master service won't have any endpoints.

**Comment by devdattakulkarni** [comment]
Thanks @AMecea for the reply.

Here are the various outputs:

kubectl describe svc my-cluster-mysql-master
Name:              my-cluster-mysql-master
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=mysql-operator,mysql_cluster=my-cluster,role=master
Type:              ClusterIP
IP:                10.97.101.54
Port:              mysql  3306/TCP
TargetPort:        3306/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

kubectl describe mysql my-cluster
Name:         my-cluster
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"mysql.presslabs.org/v1alpha1","kind":"MysqlCluster","metadata":{"annotations":{},"name":"my-cluster","namespace":"default"},"spec":{"rep...
API Version:  mysql.presslabs.org/v1alpha1
Kind:         MysqlCluster
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-02-21T23:45:44Z
  Finalizers:
    OrchestratorFinalizer
  Generation:        1
  Resource Version:  2676
  Self Link:         /apis/mysql.presslabs.org/v1alpha1/namespaces/default/mysqlclusters/my-cluster
  UID:               cdce24a5-3632-11e9-b643-080027ebd91e
Spec:
  Pod Spec:
    Affinity:
    Resources:
  Replicas:     2
  Secret Name:  my-secret
  Volume Spec:
    Persistent Volume Claim:
      Resources:
    Resources:
Status:
Events:  <none>

kubectl get pods
NAME                                                 READY     STATUS    RESTARTS   AGE
my-cluster-mysql-0                             4/4       Running           1          12h
my-cluster-mysql-1                              4/4       Running           0          12h
mysql-operator-5cf6df5bdd-nd6jk     1/1       Running           0          12h
mysql-operator-orchestrator-0            1/1       Running           2          12h

**Comment by AMecea** [comment]
Thanks! What version of Kubernetes do you use (what `kubectl version` outputs)? And what version of operator do you uses (`helm ls`)?

As I can see the cluster status is not updated, that may be because of the incompatibility between MySQL Operator and Kuberentes versions.

**Comment by devdattakulkarni** [comment]
Thanks!

Here are the versions:

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

helm ls
NAME          	REVISION	UPDATED                 	STATUS  	CHART               	NAMESPACE
mysql-operator	1       	Thu Feb 21 17:42:43 2019	DEPLOYED	mysql-operator-0.2.5	default  

Btw, I am trying this on minikube version: v0.30.0

**Comment by devdattakulkarni** [comment]
I did read this line in README: "MySQL operator 0.2.x requires at least Kubernetes 1.11.x (or 1.10.x with alpha features)"

And thought 1.10.0 version will be fine. May be not??

**Comment by AMecea** [comment]
In `1.10.x` you have to enable the alpha feature to make status subresource which is default in k8s > `1.11.x`

Please let me know if everything works!

**Comment by devdattakulkarni** [comment]
@AMecea So with latest version of minikube (0.34.0), there is some progress. I do see status for the mysql cluster and also the service has the endpoint. I am now getting access denied when I try to connect to mysql.

Here is the exact command and o/p that I am using from inside a Pod in the cluster:
mysql --host=my-cluster-mysql-master --password=bXlwYXNz --user=root
ERROR 1045 (28000): Access denied for user 'root'@'172.17.0.9' (using password: YES)

Also with the ClusterIP of my-cluster-mysql-master

mysql --host=10.103.233.142 --password=bXlwYXNz --user=root
ERROR 1045 (28000): Access denied for user 'root'@'172.17.0.9' (using password: YES)

Let me know if any other o/p will help in debugging.

**Comment by AMecea** [comment]
I think you use bas64 encoded password, only in the secret you have to encode the password.

Try:
```
mysql --host=10.103.233.142 --password=mypass --user=root
```

**Comment by devdattakulkarni** [comment]
Awesome! That works!!

It worked with both my-cluster-mysql-master and with its ClusterIP.

Thanks AMecea for the help. Appreciate it.
