### ISSUE TITLE
Question about creating clusters in different namespaces

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#239]
@AMecea I have a small question about creating clusters in different namespaces.

Is it enough to add namespace value in metadata of cluster, secret, etc. objects? Or is something more needed?

From https://github.com/presslabs/mysql-operator/issues/86 
I understand that currently the Operator watches all namespaces by default. Right? So for creating resources in different namespaces there is no need to change any Operator settings. Just including namespace in metadata should be enough. Is my understanding correct?

**Comment by AMecea** [comment]
Hi @devdattakulkarni, Yes, you are correct, by default the operator watches all namespaces, just set `.metadata.namespace` field on MySQL cluster resource and on the credentials secret.

**Comment by devdattakulkarni** [comment]
Cool! Thanks @AMecea 
I will try that and will add comment here if I run into any issues.

**Comment by devdattakulkarni** [comment]
@AMecea I am getting following error when trying to create cluster in a namespace.

Note that the name of the namespace that I am using is 'namespace1'.

{"level":"warn","ts":1550969299.8232875,"logger":"controller.orchestrator","msg":"can't get master from orchestrator","alias":"cluster1.namespace1","error":"[orc]: status: 500 path: master/cluster1.namespace1 msg: 2019-02-24 00:48:19 ERROR Unable to determine cluster name. clusterHint=cluster1.namespace1, details: <nil>","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*infoLogger).Info\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:69\ngithub.com/presslabs/mysql-operator/pkg/controller/orchestrator.(*orcUpdater).Sync\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/orchestrator/orchestrator_reconcile.go:83\ngithub.com/presslabs/mysql-operator/vendor/github.com/presslabs/controller-util/syncer.Sync\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/presslabs/controller-util/syncer/syncer.go:62\ngithub.com/presslabs/mysql-operator/pkg/controller/orchestrator.(*ReconcileMysqlCluster).Reconcile\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/orchestrator/orchestrator_controller.go:199\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1550969299.8233798,"logger":"controller.orchestrator","msg":"discovering hosts","keys":null}
{"level":"info","ts":1550969299.8233979,"logger":"controller.orchestrator","msg":"setting cluster in read-only","cluster":"cluster1.namespace1"}

**Comment by AMecea** [comment]
That's a warning message and it's normal to appear, few times when a cluster is created. Is the cluster created successfully?

**Comment by devdattakulkarni** [comment]
@AMecea It did work after a while.
