### ISSUE TITLE
How to specify the orchestrator password?

### ISSUE THREAD

**Issue by linqingping** [presslabs/mysql-operator#262]
How to specify the orchestrator password? @AMecea  can you help me?

**Comment by AMecea** [comment]
In your `values.yaml` file or if you are using [helm secrets](https://github.com/futuresimple/helm-secrets) in `secrets.yaml` file add the following:

```yaml
orchestrator:
  topologyPassword: the-password
```

And when deploying run:
 `helm upgrade --install <release-name> presslabs/mysql-operator -f values.yaml`

**Comment by linqingping** [comment]
Thank you for help！Thank you very much! @AMecea
