### ISSUE TITLE
the service not use

### ISSUE THREAD

**Issue by linqingping** [presslabs/mysql-operator#267]
![image](https://user-images.githubusercontent.com/20528139/54762819-c8f23080-4c2f-11e9-8ad6-5e499ba65e49.png)

**Comment by AMecea** [comment]
What is the status of the MySQL cluster (`kubectl describe mysql my-cluster`)?

**Comment by AMecea** [comment]
Also, I've notice that you are running the `mysql-client` pod in `mysql-operator` namespace but the cluster is deployed in `default` namespace. If so, you have to append the namespace to the service as `my-cluster-mysql-master.default`

**Comment by linqingping** [comment]
Thank you for help！ @AMecea
