### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by AMecea** [presslabs/mysql-operator#29]
- [x] create cluster
- [x] cluster scale-up
- [x] cluster scale-down
- [x] node removed from service when latency > `spec.maxSlaveLatency`
- [x] node removed from service when not replicating
- [x] `spec.readOnly` flag with failover
- [ ] update nodes when mysql config changes
- [ ] change in cpu, memory (storage size) config of mysql object

**Comment by calind** [comment]
Closed by #123
