### ISSUE TITLE
Error installing Operator

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#294]
When trying to deploy the Operator using Helm commands given in the README, I am getting following error:

$ kubectl get pods
NAME                             READY     STATUS             RESTARTS   AGE
mysql-operator-77bb98ff7-hcv72   0/1       CrashLoopBackOff   5          4m
mysql-operator-orchestrator-0    1/1       Running            3          4m

kubectl logs mysql-operator-77bb98ff7-hcv72
{"level":"info","ts":1554660708.7858343,"logger":"mysql-operator","msg":"Starting mysql-operator..."}
{"level":"info","ts":1554660708.8846366,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mysqlbackup-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1554660708.8852034,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MysqlBackup.mysql.presslabs.org","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlbackup.add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlbackup/mysqlbackup_controller.go:76\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlbackup.Add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlbackup/mysqlbackup_controller.go:54\ngithub.com/presslabs/mysql-operator/pkg/controller.AddToManager\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/controller.go:29\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:94\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
{"level":"error","ts":1554660708.888549,"logger":"mysql-operator","msg":"unable to setup controllers","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}

Kubernetes versions:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by AMecea** [comment]
Hi @devdattakulkarni, what version of helm do you have installed?

Helm is responsible for installing CRDs, we use helm [capabilities API](https://github.com/helm/helm/blob/master/docs/chart_template_guide/builtin_objects.md) which are available from version `2.2.0`.

**Comment by devdattakulkarni** [comment]
Thanks. This is good info. My Helm version is:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Btw, the issue has been intermittent. After deleting my Minikube VM and trying operator installation again, things have been working. You can close the issue. But I wanted to report it in case any code level changes need to happen.

**Comment by jmaitrehenry** [comment]
I have the exact same problem using an AKS cluster with helm v2.9.1.

@AMecea can you reopen the issue ?

```
$ kubectl get pods
NAME                             READY     STATUS             RESTARTS   AGE
mysql-operator-547cfc796-2d6l2   0/1       CrashLoopBackOff   503        1d
mysql-operator-orchestrator-0    1/1       Running            1          1d
```

```
{"level":"error","ts":1559749695.6542397,"logger":"mysql-operator","msg":"unable to setup controllers","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
```

```
$ kubectl logs mysql-operator-547cfc796-2d6l2 
{"level":"info","ts":1559749695.5175185,"logger":"mysql-operator","msg":"Starting mysql-operator..."}
{"level":"info","ts":1559749695.6539948,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mysqlbackup-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1559749695.6540716,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MysqlBackup.mysql.presslabs.org","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlbackup.add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlbackup/mysqlbackup_controller.go:76\ngithub.com/presslabs/mysql-operator/pkg/controller/mysqlbackup.Add\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/mysqlbackup/mysqlbackup_controller.go:54\ngithub.com/presslabs/mysql-operator/pkg/controller.AddToManager\n\t/go/src/github.com/presslabs/mysql-operator/pkg/controller/controller.go:29\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:94\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
{"level":"error","ts":1559749695.6542397,"logger":"mysql-operator","msg":"unable to setup controllers","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
```

**Comment by AMecea** [comment]
We use `crd-install` helm hook to install CRDs. This hook is introduced in helm version `v2.10.0` and above.

Please let me if updating helm to newer version fixes your problem.

**Comment by jmaitrehenry** [comment]
@AMecea It works.
Maybe we could update the note in the README.md to includes the minimum version of helm. I could make a PR if you want for that.

The note in question:
> NOTE: MySQL operator 0.2.x requires at least Kubernetes 1.11.x (or 1.10.x with alpha features) while version 0.1.x is known to work with Kubernetes up 1.9.x. To upgrade, check the 0.2.x upgrade notes as some additional steps are required.

**Comment by AMecea** [comment]
It's a good idea. I will be happy to merge that PR!

**Comment by Hugh-ifly** [comment]
I have the exact same problem using an bare-metal k8s cluster with helm v3.0.0-alpha.1.

**Comment by AMecea** [comment]
Helm version 3 introduced major changes. We didn't test the mysql-operator chart with helm version 3 yet because helm is still in alpha.

If you spot the incompatibilities in the helm chart please open another issue to upgrade chart to be comptible with helm 3. Thanks!

**Comment by etiennejournet** [comment]
Hello,

It still doesn't work with Helm3 :  
`{"level":"error","ts":1576852138.0194187,"logger":"mysql-operator","msg":"unable to setup controllers","error":"no matches for kind \"MysqlBackup\" in version \"mysql.presslabs.org/v1alpha1\"","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/presslabs/mysql-operator/cmd/mysql-operator/main.go:95\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

best practice for crds in helm 3 : https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/
