### ISSUE TITLE
AWS Secret key name

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#301]
For taking backups, the secret that needs to be created currently needs following keys:
- AWS_ACCESS_KEY_ID:
- AWS_SECRET_KEY: 

I was wondering if it will be possible to change the key AWS_SECRET_KEY to AWS_SECRET_ACCESS_KEY.

The reason is doing so will make the key name same as that used by aws cli.
As reference, the ~/.aws/credentials file has following key names:
- aws_access_key_id
- aws_secret_access_key

**Comment by abh** [comment]
it's confusing that the documentation on the website has been updated, but this not released (other than as a release candidate...).   (And by confusing I meant it took a lot of debugging to figure out that the documentation didn't match the released version).
