### ISSUE TITLE
Pod fails to schedule (Operator Pod and Cluster Pod)

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#310]
I am trying this Operator on a Single node DigitalOcean cluster (8 vCPUs, 16GB memory). I have been seeing following error on the Operator Pod and the MySQL cluster Pod. 

This is output of 'kubectl describe pod-name' (on Operator Pod and MysqlCluster Pod). Both the errors look similar. 
"
  Warning  FailedScheduling  16s (x13 over 6m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
"

Both the errors seem intermittent. Sometimes everything works smoothly, at other times either the Operator Pod becomes stuck, or if the Operator Pod deploys correctly, the MySQL cluster Pod becomes stuck. 

Have you seen this error? Any suggestions on how to prevent this from happening?

**Comment by AMecea** [comment]
Hi @devdattakulkarni, I'm not aware of this issue. 

What storage class do you have configured, also what PV provisioner do you use? This happens, few times, but because the provisioner delayed PVC creation.

Please let me know how you solve this

**Comment by AMecea** [comment]
Hi @devdattakulkarni, I will close this issue, please feel free to open it again, if this happens again!

**Comment by devdattakulkarni** [comment]
@AMecea Sounds good.
