### ISSUE TITLE
Orchestrator doesn't do recovery after detecting a failover

### ISSUE THREAD

**Issue by sxy630707** [presslabs/mysql-operator#322]
I used the latest operator image v0.3.0-rc.1.
I launched a MySQL cluster with 3 members, one master and two secondaries. The Orchestrator web UI show their status correctly at very beginning. But I got some error message in Orchestrator log
`ReadTopologyInstance(my-cluster-mysql-0.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
`ReadTopologyInstance(my-cluster-mysql-1.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
`ReadTopologyInstance(my-cluster-mysql-2.mysql.default:3306) ReplicationLagQuery: Error 1142: SELECT command denied to user 'orchestrator'@'10.244.79.203' for table 'heartbeat'`
I found out that mysql user orchestrator did not have privileges on table heartbeat so I GRANT privileges manually for each mysqld.
I used `kubectl delete pod my-cluster-mysql-0 --grace-period=0 --force` to delete master.
The Orchestrator detected the master is unreachable
`Detected: 2019-05-15T23:29:43Z`
`2 replicating hosts :`
`my-cluster-mysql-2.mysql.default:3306`
`my-cluster-mysql-1.mysql.default:3306`
`Changelog :`
`2019-05-15T23:29:43Z UnreachableMaster,`
It, however, did not take any step to automatically recover the failure. There is no secondary to be promoted to the new master.
Can anyone help me with this issue?

**Comment by AMecea** [comment]
Thanks for reporting this! I've already started to fix the permissions for the operator user, to be able to access `heartbeat` table, see 20a5971609ec71cce3a741d23a75984dfa701b9f.

As for the failover I will do some tests, asap.

Thanks!

**Comment by sxy630707** [comment]
Thank you! Please let me know when this bug got fixed. I appreciate it.

**Comment by AMecea** [comment]
I've tried with deleting the pod with `--force --grace-period=0` but the deletion and recreation were too fast and the orchestrator didn't consider that a failover is necessary. Is this the case that happened to you?

**Comment by sxy630707** [comment]
I have no idea. Based on the Orchestrator web UI, it does detect the failover but the recovery never happen.

**Comment by AMecea** [comment]
I ran few tests and if the pod came up fast enough orchestrator doesn't perform failover, without mentioning that the failover is too fast.
