### ISSUE TITLE
install mysql-operator error

### ISSUE THREAD

**Issue by Jacklli** [presslabs/mysql-operator#337]
# helm install presslabs/mysql-operator --name mysql-operator
Error: parse error in "mysql-operator/charts/orchestrator/templates/statefulset.yaml": template: mysql-operator/charts/orchestrator/templates/statefulset.yaml:27: function "nindent" not defined

**Comment by Jacklli** [comment]
# helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

**Comment by AMecea** [comment]
Hi, what version of helm do you have installed? 'nindent` function is added to helm from version v2.7

**Comment by Jacklli** [comment]
after upgrading helm from 2.6.1 to 2.12.3, it's fixed. Thanks for your help.
