### ISSUE TITLE
Can't start cluster, init-mysql container error

### ISSUE THREAD

**Issue by jerbob92** [presslabs/mysql-operator#343]
I tried out the operator today, but I can't get the cluster to start. The init-mysql container gives the following error:
`sidecar	error while reading PURGE GTID from xtrabackup info file	{"error": "open /var/lib/mysql/xtrabackup_binlog_info: no such file or directory"}`
Anyone has seen this before? Can't find much about it.

**Comment by jerbob92** [comment]
I think the problem was that I did not base64 my ROOT_PASSWORD. Not sure why that results in this error though.

**Comment by AMecea** [comment]
That message is normal for the first node (if the cluster is not initialized from a backup). Maybe I will change the text in something more clear, that's not an error its an info message. Thanks for pointing it out!
