### ISSUE TITLE
"secret_access_key not found" - backup not working

### ISSUE THREAD

**Issue by vitobotta** [presslabs/mysql-operator#345]
Hi! I am having a problem with backups failing. The logs of the pod show the message in the subject as if it can't read the backup secret or something. However the backup secret exists and has the correct keys, plus I have been using exactly the same settings and automated procedures a ton of times this past week without any problems. Has anything changed since yesterday? I am installing with Helm. I also checked the example yamls for the cluster etc just in case some variable names had changed or something, but it looks like I am up to date. 

Like I said it was working until yesterday with the same settings - I am automating things so I haven't done anything different this time. Any idea of why the sidecar  can't find the secret_access_key? Thanks in advance.

**Comment by vitobotta** [comment]
`/etc/rclone.conf` in the sidecar has empty settings but the secret definitely exists

**Comment by vitobotta** [comment]
I am wondering if this is related to the fact that soon after the cluster is created, its pods are terminated and recreated automatically both with 0.2.9 and 0.3.0.rc-1. Could that be the reason why the rclone s3 settings are empty?

**Comment by AMecea** [comment]
Hi @vitobotta, version 0.3.0 has few major changes but that should not affect backup secret. Also `v0.3.0-rc.1` has a few issues. I will create a new release in a few minutes.

**Comment by vitobotta** [comment]
Hi @AMecea ! If I add that `envFrom` section with the backup secret, all works. It looks like it's missing somehow. I tried to look in the code but I can't find the template for the cluster statefulset :)

**Comment by AMecea** [comment]
Can you please give the backup specification and the cluster specification by running `kubectl descibe mysql <cluster-name>` and `kubectl describe mysqlbackup <backup-name>`.

The env is set on the backup job, [here](https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/mysqlbackup/internal/syncer/job.go#L164).

**Comment by vitobotta** [comment]
Sure, there are [here](https://ybin.me/p/8a6a0318b68f0f15#XmW46r3Kw+6HwcqcdV9gf1F0YmQlf2Te1LLCYeh4BdE=) and [here](https://ybin.me/p/7bd827e9409f7f82#vT9k4MBbKwHORz6QFALhFLwjSWqsOAxCeHLWdBF7fzw=). 

Then [this](https://ybin.me/p/a8a1ce651ed39708#3R2l0MxlC3WFc+0HbALX5NIBTBUue+Iv0jEuDkSyjqw=) is the log of one pod created by the backup job. It's creating pods all the time because they crash. Thanks!

**Comment by AMecea** [comment]
Is there a chance that you migrate to version `0.3.0-rc.1` then back to version `v0.2.x`? If so the migration back to a lower version has an undefined behavior. You have to manually delete the statefulset of the cluster and let the operator recreate it.

Also in version 0.3.0  the `AWS_SECRET_KEY` was renamed to `AWS_SECRET_ACCESS_KEY` but in the next release both of them will be supported, see this [commit](https://github.com/presslabs/mysql-operator/commit/312f51aa50420eea8a29531daed4bc29996e62e1#diff-7fff341ad1d6d4eb0a228543517f46d6). After passing the build I will do the release.

**Comment by AMecea** [comment]
`v0.3.0-rc.3` is out! Please let me know if you encounter the same issue with the new version. (Don't forget to update the helm chart by running `helm repo update`

**Comment by vitobotta** [comment]
@AMecea I may have installed 0.2.9 after 0.3.0 to try but it was because of this very issue. I did an uninstall/cleanup first though. I'll try the rc3 now :)

**Comment by vitobotta** [comment]
So I purged the release, deleted the mysql namespace  (where I install both the operator and the cluster), and installed rc3. It did two backups successfully, so it seems to be fixed whatever it was :D I'll uninstall / reinstall a couple of times though just to be sure I wasn't lucky :D

Has something changed about the orchestrator? It hasn't created the orchestrator pod.

**Comment by AMecea** [comment]
Yes, the orchestrator is now in the same pod with the controller. When you scale the controller the orchestrator is scaled too. But for now orchestrator doesn't work well with multiple replicas.

**Comment by vitobotta** [comment]
BTW also with rc3 shortly after a cluster is created and is up and running, it is terminated and reinitialised/restarted :)

**Comment by vitobotta** [comment]
> Yes, the orchestrator is now in the same pod with the controller. When you scale the controller the orchestrator is scaled too. But for now orchestrator doesn't work well with multiple replicas.

Ah OK :)

**Comment by vitobotta** [comment]
I uninstalled/reinstalled another couple of times and backups worked each time. Thanks! 👍

**Comment by vitobotta** [comment]
I am closing now since the problem seems to have gone :)
