### ISSUE TITLE
Cannot delete cluster

### ISSUE THREAD

**Issue by nn-afly** [presslabs/mysql-operator#349]
How can i delete/remove the cluster from my k8s install? It wasn't removed with a helm purge and commands like the following

kubectl delete mysql db-cluster --grace-period=0 --force

Tell me it is deleted but doesn't release the cli session, a subsequent  kubectl get mysql show's it is still there

this is 1.13.5 on digitial ocean

**Comment by AMecea** [comment]
On the cluster is added a finalizer, to prevent cluster deletion until is removed from k8s. 

So you either remove that finalizer by hand by running `kubectl edit mysql db-cluster` or you reinstall the operator to remove the finalizer itself.

**Comment by nn-afly** [comment]
Thank you this fixed my issue. I wasn't able to reinstall as it was getting errors relating to the creations of the stateful set(s). killing the finalizer and reinstalling has got me back up and running

**Comment by pickfire** [comment]
This is not a fix but just a workaround, can you please reopen the issue? We always have the issue such that the namespace is the only thing left but all the pods and stuff are deleted, and presslab finalizer is always there, it only creates it and never deletes it. Is there a way to not manually remove the finalizer by hand? We remove all stuff by `kubectl delete -k deploy/overlays/dev/`.

**Comment by jdbranham** [comment]
I know this issue is closed, but I'm still seeing the same behavior.   
(the operator is installed - I'm just trying to delete the DB and User objects)
