### ISSUE TITLE
RemoteDeletePolicy for auto backup is needed

### ISSUE THREAD

**Issue by bluven** [presslabs/mysql-operator#351]
I just found that MysqlBackup have a RemoteDeletePolicy field. But RemoteDeletePolicy of auto backups is `retain`, which means users have to delete physical backups from remote storage manually. 

Can we support  RemoteDeletePolicy in MysqlClusterSpec to support automatic deletion of remote storage?

**Comment by AMecea** [comment]
Hi @bluven, This field was added recently in version `0.3.0-rc.3`. More information can be found [here](https://github.com/presslabs/mysql-operator/blob/766484f6b64f1a87d380f7fa1cac29089df4f17e/pkg/apis/mysql/v1alpha1/mysqlcluster_types.go#L83).

**Comment by bluven** [comment]
Great! Thanks!
