### ISSUE TITLE
Please use explicit image tag rather that `latest` in chart

### ISSUE THREAD

**Issue by bluven** [presslabs/mysql-operator#353]
All container images in `hack/charts/mysql-operator/values.yaml` use tag `latest`, I think it's better to use explicit tag like `v0.3.0`, `v0.3.0-rc.3`, otherwise it's really easy to install mysql-operator with wrong images. In fact this happened once, so to avoid this problem I have to install mysql-operator like this
```
helm install \
    --name mysql-operator \
    --version 0.2.7 \
    presslabs/mysql-operator \
    --set image=${REPO_PREFIX}/mysql-operator:0.2.7 \
    --set sidecarImage=${REPO_PREFIX}/mysql-operator-sidecar:0.2.7 \
    --set extraArgs={--metrics-exporter-image=${REPO_PREFIX}/mysqld-exporter:v0.11.0} \
    --set orchestrator.image=${REPO_PREFIX}/orchestrator:v3.0.14-r37
    --set orchestrator.orchestratorConf.InstancePollSeconds=10
```

**Comment by AMecea** [comment]
We pin the images to the correct version. Before publishing the chart exists a build [step](https://github.com/presslabs/mysql-operator/blob/766484f6b64f1a87d380f7fa1cac29089df4f17e/.drone.yml#L51) where the chart images and version are updated. This is the [script](https://github.com/presslabs/mysql-operator/blob/master/hack/generate_chart.sh) that updates the chart.

Can you give me an example when the images are not with the right tag?

Thank you!

**Comment by bluven** [comment]
@bluven Sorry, cannot make it happen again and I guess I had a wrong judgement.
