### ISSUE TITLE
Pod ''mysql-operator-orchestrator'' is pending after helm install 

### ISSUE THREAD

**Issue by gjj2016** [presslabs/mysql-operator#360]
follow this guide to install the mysql-operator with helm version v1.13.0 :>
>   helm repo add presslabs https://presslabs.github.io/charts
   helm install presslabs/mysql-operator --name mysql-operator

everything is ok but the pod "mysql-operator-orchestrator-0"  is always in pending:

> [node1@node1 nfs-provied]$ kubectl get pod 
>NAME                                                 READY   STATUS       RESTARTS   AGE
>mysql-operator-6fccc6547b-pfn59    1/1         Running     0                 5s
>mysql-operator-orchestrator-0          0/1         Pending      0                5s

i check the persistentvolumeclaim is always pending, and no persistentvolume is available.

**Comment by AMecea** [comment]
What version of k8s do you use? Also, please make sure that PVC can be created and are provisioned.

Also, a description of that pod can help (`kubectl describe mysql-operator-orchestrator-0 `)

**Comment by gjj2016** [comment]
The k8s version is v1.14.3
here is the PVC infomation:
>Name:          data-mysql-operator-orchestrator-0
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=mysql-operator-orchestrator
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                      From                         Message
  Normal     FailedBinding  2m12s (x803 over 3h22m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

But no pv:
>[node1@node1 nfs-provied]$ kubectl get pv
No resources found.

here is the describe of the pending pod:
>Name:               mysql-operator-orchestrator-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=mysql-operator-orchestrator
                    controller-revision-hash=mysql-operator-orchestrator-d94b56c6d
                    statefulset.kubernetes.io/pod-name=mysql-operator-orchestrator-0
Annotations:        checksum/config: 99d637ad59c9ace3efc54980eb6452f4d9a8ad1fa1d4942a74e1d54f11356ee3
                    checksum/secret: 46b7340385dc5895e30a33aa6e9b7c7ca7f9add8dc7aba8c822151e1e843f5ad
Status:             Pending
IP:                 
Controlled By:      StatefulSet/mysql-operator-orchestrator
Containers:
  orchestrator:
    Image:       quay.io/presslabs/orchestrator:v3.0.13-r29
    Ports:       3000/TCP, 10008/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:3000/api/lb-check delay=200s timeout=10s period=10s #success=1 #failure=3
    Readiness:   http-get http://:3000/api/raft-health delay=0s timeout=10s period=10s #success=1 #failure=3
    Environment Variables from:
      mysql-operator-orchestrator  Secret with prefix 'ORC_'  Optional: false
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /templates/ from config (rw)
      /var/lib/orchestrator/ from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t8cqv (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-mysql-operator-orchestrator-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mysql-operator-orchestrator
    Optional:  false
  default-token-t8cqv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-t8cqv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  Warning  FailedScheduling  67s (x33 over 47m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

**Comment by gjj2016** [comment]
@AMecea 

The k8s version is v1.14.3
here is the PVC infomation:

>Name: data-mysql-operator-orchestrator-0
Namespace: default
StorageClass:
Status: Pending
Volume:
Labels: app=mysql-operator-orchestrator
Annotations: 
Finalizers: [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode: Filesystem
Events:
Type Reason Age From Message
Normal FailedBinding 2m12s (x803 over 3h22m) persistentvolume-controller no persistent volumes available for this claim and no storage class is set

But no pv:

>[node1@node1 nfs-provied]$ kubectl get pv
No resources found.

here is the describe of the pending pod:

>Name: mysql-operator-orchestrator-0
Namespace: default
Priority: 0
PriorityClassName: 
Node: 
Labels: app=mysql-operator-orchestrator
controller-revision-hash=mysql-operator-orchestrator-d94b56c6d
statefulset.kubernetes.io/pod-name=mysql-operator-orchestrator-0
Annotations: checksum/config: 99d637ad59c9ace3efc54980eb6452f4d9a8ad1fa1d4942a74e1d54f11356ee3
checksum/secret: 46b7340385dc5895e30a33aa6e9b7c7ca7f9add8dc7aba8c822151e1e843f5ad
Status: Pending
IP:
Controlled By: StatefulSet/mysql-operator-orchestrator
Containers:
orchestrator:
Image: quay.io/presslabs/orchestrator:v3.0.13-r29
Ports: 3000/TCP, 10008/TCP
Host Ports: 0/TCP, 0/TCP
Liveness: http-get http://:3000/api/lb-check delay=200s timeout=10s period=10s #success=1 #failure=3
Readiness: http-get http://:3000/api/raft-health delay=0s timeout=10s period=10s #success=1 #failure=3
Environment Variables from:
mysql-operator-orchestrator Secret with prefix 'ORC_' Optional: false
Environment:
POD_IP: (v1:status.podIP)
Mounts:
/templates/ from config (rw)
/var/lib/orchestrator/ from data (rw)
/var/run/secrets/kubernetes.io/serviceaccount from default-token-t8cqv (ro)
Conditions:
Type Status
PodScheduled False
Volumes:
data:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: data-mysql-operator-orchestrator-0
ReadOnly: false
config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: mysql-operator-orchestrator
Optional: false
default-token-t8cqv:
Type: Secret (a volume populated by a Secret)
SecretName: default-token-t8cqv
Optional: false
QoS Class: BestEffort
Node-Selectors: 
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message
Warning FailedScheduling 67s (x33 over 47m) default-scheduler pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

**Comment by AMecea** [comment]
Hi @gjj2016, did you manage to fix this?

It seems that the storage class is not set and there is not default storage class created.

**Comment by gjj2016** [comment]
Hi @AMecea , so i have to give a storage class before i do this ?
> helm install presslabs/mysql-operator --name mysql-operator

**Comment by AMecea** [comment]
Usually no but if you don't have a default storage class specified then you should set one. What `kubectl get storageclass` outputs?

To set a storage class use the following command:
```
helm install presslabs/mysql-operator --name mysql-operator --set orchestrator.persistence.storageClass=<your storage class here>
```

But you have to set a default one else you have to specify for each new mysql cluster a storage class in order to work.

**Comment by gjj2016** [comment]
@AMecea 
Score! It's amazing after i tried to set a storage class. It works. Thanks for your help.

**Comment by AMecea** [comment]
I'm glad it works! I will close it. Please let me know if you encounter any issues.

Best regards,

**Comment by gjj2016** [comment]
@AMecea 
Thank you very much!

Best regards,

**Comment by kevinbin** [comment]
How should this parameter orchestrator.persistence.storageClass be set? If using local disk 
orchestrator.persistence.storageClass=Local ?

**Comment by AMecea** [comment]
Hi @kevinbin ,

Using `orchestrator.persistence.storageClass` you can specify which [storage class](https://kubernetes.io/docs/concepts/storage/storage-classes/) to use.
To see what storage classes you have run `kubectl get storageclass`. Usually, this can be empty and then the default storage class is used. (make sure that you have a default storage class set)
