### ISSUE TITLE
Define side car resources configuration

### ISSUE THREAD

**Issue by kman99** [presslabs/mysql-operator#377]
Sidecar container resource limits are too low and are continuously being throttled down.

Having the ability to override this can will enable users to define sane values for their environment.

```  Containers:
   sidecar:
    Limits:
      cpu:  50m
    Requests:
      cpu:      10m
   metrics-exporter:
    Limits:
      cpu:  100m
    Requests:
      cpu:     10m
   pt-heartbeat:
    Limits:
      cpu:  50m
    Requests:
      cpu:  10m```

**Comment by AMecea** [comment]
Hi @kman99, the operator has support for setting metrics exporter and sidecar container resources, starting from version `0.4.0`.
