### ISSUE TITLE
[Metrics-Exporter] level=error msg="Error scraping for collect.heartbeat: Error 1146: Table 'sys_operator.heartbeat' doesn't exist" source="exporter.go:138"

### ISSUE THREAD

**Issue by imriss** [presslabs/mysql-operator#378]
In deploying a `MySQL` cluster using the `MySQL Operator` via `Helm`, the first pod got stuck at 3/4 with following error in the `metrics-exporter` container:
```
time="2019-07-30T21:32:17Z" level=info msg="Listening on 0.0.0.0:9125" source="mysqld_exporter.go:232"
time="2019-07-30T21:32:23Z" level=error msg="Error pinging mysqld: dial tcp 127.0.0.1:3306: connect: connection refused" source="exporter.go:119"
time="2019-07-30T21:32:38Z" level=error msg="Error scraping for collect.heartbeat: Error 1146: Table 'sys_operator.heartbeat' doesn't exist" source="exporter.go:138"
```

The version of `MySQL`:
```
2019-07-30T21:32:27.076385Z 0 [Note] mysqld (mysqld 5.7.24-26-log) starting as process 1 ...
```

Deleting the cluster and re-deploying it using `Helm` did not make any difference.

Any advise? Thanks

**Comment by imriss** [comment]
After 4 hours, the first pod (`-0`) became ready, however now the second pod (`-1`) was stuck at `readiness probe failed` even after 7 hours.

**Comment by AMecea** [comment]
Hello @imriss,

It is possible that the operator was not running, during that time? I hit a similar issue before, but in my case, the operator was not running. 

Please provide me more details. What `kubectl describe pod <pod-name>` returns?

Also, show me the logs of the `mysql` container. The `sys_operator` database, the metrics and pt-heartbeat users are created using [mysql init file](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_init_file). So if there were some errors in that files can be shown in `mysql` container. The init file can be found in the `mysql` container under `/etc/mysql/conf.d/operator-init.sql`.

The `heartbeat` table is created by the `pt-heartbeat` tool. Show me the logs of that container too.

Thank you for reporting and helping debugging this!

**Comment by imriss** [comment]
Hello @AMecea Sorry for the delay. The operator was running at that time. I guess that it was something related to the environment (the VM). After deploying the whole cluster, the error did not repeat.
