### ISSUE TITLE
Option to deploy using manifests instead of Helm charts

### ISSUE THREAD

**Issue by cpanato** [presslabs/mysql-operator#384]
Today there is no option to deploy the operator using only the manifests, the only way is to use helm.

Is that possible to add the manifests in the repo as well? otherwise need to render the templates from helm to generate those

thanks!

**Comment by AMecea** [comment]
Hi @cpanato, 

An idea could be to generate with helm template all manifests and to commit them to the repo. If you are willing to contribute, please open a PR and we are glad to review and merge it.

**Comment by cpanato** [comment]
ok cool, will check we can close this for now
