### ISSUE TITLE
Can't seem to install anymore

### ISSUE THREAD

**Issue by dlebee** [presslabs/mysql-operator#387]
Hello, for some reason now when i try to install it does not create any pvc, and I can't login to the mysql.

I made it work in the past, I tried re-creating the whole cluster same thing?

is there anything new I should know?
where should I start looking?

**Comment by AMecea** [comment]
Hi @dlebee,

Can you please give me more details(e.g. logs, describe on pod/sts)?

Thank you!

**Comment by dlebee** [comment]
Sorry I can't I moved on to another package and got rid of the pods.
