### ISSUE TITLE
Writes going to old master during failover due to race condition

### ISSUE THREAD

**Issue by dougfales** [presslabs/mysql-operator#411]
This issue came up for us during our evaluation of the operator this month. My colleague @stankevich was testing the behavior of the operator during failover when he found that a client which writes continuously during a failover could cause writes to go to the old master, breaking replication and causing errant GTIDs on the old master.  We have a fix which I would like to submit as a PR if you think our solution is acceptable.

Specifically, the issue we are seeing is that, when the cluster experiences a failover during high write activity, there is a window during which the `orcUpdater`'s `markReadOnlyNodesInOrc` function will [interfere](https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/orchestrator/orchestrator_reconcile.go#L508) with Orchestrator's readable/writable settings, permitting writes to go to the old master. The result is that the old master has writes which are not replicated to the rest of the cluster, and Orchestrator shows it as having errant GTIDs. It may also be unable to rejoin the cluster as a replica.

## Steps to Reproduce

1. Create a script which is continuously writing to the master. The more frequently it writes, the more likely it will reproduce this case.
2. While this client is actively writing, promote another mysql instance to master, either using the Orchestrator API (`/graceful-master-takeover/$cluster/$new-master`) or the Orchestrator UI.
3. Observe the state of the cluster in Orchestrator. If writes were delivered to the old master during the promotion, then the cluster will show the *errant GTID* (the red globe icon) state, and one of the replicas may be red to indicate that replication is not running.

## Proposed Solution

The solution we've implemented is very similar to the check used in [the `ReconcileMysqlNode.Reconcile` function](https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/node/node_controller.go#L230-L231), where the reconciliation is skipped if the status of `ClusterConditionFailoverInProgress` is true. 

Rather than skip the entire iteration of `orcUpdater.Sync`, we perform [this check in `markReadOnlyNodesInOrc` and return early](https://github.com/dougfales/mysql-operator/commit/4cbacdd42e279d8f6696b93f65965988b49359b1) if there's a failover in progress. This allows the `Sync` function to continue and unset the `ClusterConditionFailoverInProgress` later in [`updateStatusFromOrc`](https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/orchestrator/orchestrator_reconcile.go#L263-L264).

If you agree with this solution, I would be happy to submit a PR with our fix.

**Comment by AMecea** [comment]
Hi @dougfales,

Sorry for the delay, yes it sounds good to me, and the code looks good, please open a PR, I will be happy to review it and merge it. Also, I will do a few more tests to make sure that it does not introduce regressions.

I'm glad you tested the operator and **thank you** for reporting the issues you find!
Best regards,

**Comment by dougfales** [comment]
Sounds great @AMecea, I will open a PR with the fix very soon. And thank *you* for building the operator and making it available!

**Comment by dougfales** [comment]
Thanks for merging my changes @AMecea! Going to close this now...

**Comment by drivebyer** [comment]
I am so happy to see that there is already an issue on the case. However, I found that the PR #417 does not solve this completely. I will open another issue to track it.
