### ISSUE TITLE
Confusing "cluster failover finished" message being logged every sync

### ISSUE THREAD

**Issue by tanordheim** [presslabs/mysql-operator#414]
I've just spent a little while trying to figure out why the operator was continuously logging "cluster failover finished". After [checking the code](https://github.com/presslabs/mysql-operator/blob/c29428dca7dc63479c3f7d820e702baf1de4503a/pkg/controller/orchestrator/orchestrator_reconcile.go#L261), it seems to me that this message is logged every reconciliation loop as long as the master node has been seen within the last few seconds - regardless of if a failover has recently happened or not.

Is this intended? It caused me some needless confusion here this morning after testing out the operator and seeing this logged quite often, leading me to think that the cluster was stuck in some kind of failover-loop while at the same time I was unable to see any indications of that in the orchestrator logs/web UI or in the MySQL pod logs. I'd be happy to provide a PR for a fix if I can get some input on what the appropriate logging behavior here would be.

**Comment by AMecea** [comment]
Hi @tanordheim,

That was not intended :smile:  It is a leftover from when I was doing debugging.
Maybe it will be useful to log within the else branch that the master server is not seen by the orchestrator.

So, PR is welcome!

Thanks!
