### ISSUE TITLE
"the master has purged binary logs containing GTIDs that the slave requires"

### ISSUE THREAD

**Issue by abh** [presslabs/mysql-operator#425]
When adding a new replica I now get this error:

```
"Got fatal error 1236 from master when reading data from binary log:
'The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1,
but the master has purged binary logs containing GTIDs that the slave requires.'"
```

How does this happen?

**Comment by abh** [comment]
The active master is `db-1` and the new (starting from blank) replica is `db-0`.

I just noticed that `db-0` didn't start with a snapshot of `db-1`, as it has worked otherwise when a new replica entered the system.  `db-0` just has a blank database.

**Comment by AMecea** [comment]
Hi @abh, 

Is this issue related to #412 and #326?

Thank you for your contribution!

**Comment by abh** [comment]
Yes, I think this issue is a duplicate of those. Thank you!

(That explains why it came up now after upgrading to 0.3.x since I'd seen the system automatically take care of this scenario before).
