### ISSUE TITLE
Upgrade Orchestrator?

### ISSUE THREAD

**Issue by abh** [presslabs/mysql-operator#427]
(I'm still fussing with the 3 clusters that lost their replicas when upgrading the mysql-operator last weekend).

One of the clusters ran into the MySQL bug that's worked around in this https://github.com/github/orchestrator/pull/807

I think it's included in the Orchestrator releases from this summer; but mysql-operator includes the one from January.

**Comment by AMecea** [comment]
Hi @abh,

This is a good idea, I will love to review and merge a PR that does that.

Best regards,

**Comment by abh** [comment]
See #428
