### ISSUE TITLE
option to clean up cron jobs

### ISSUE THREAD

**Issue by jserviceorg** [presslabs/mysql-operator#435]
is it somehow possible to automatically clean finished backup job leftovers? something like kubernetes   ttlSecondsAfterFinished ?

**Comment by AMecea** [comment]
Hi @jserviceorg, you can set a history limit per cluster. See this [example](https://github.com/presslabs/mysql-operator/blob/0e8f3e2129ca12e83cd974ac097a9c309eaa98ca/examples/example-cluster.yaml#L19).

Hope this helps!

**Comment by jserviceorg** [comment]
oh i missed that one :) thanks!

**Comment by neumantm** [comment]
Does this option only delete the job, or is the backup itself also deleted?

**Comment by jserviceorg** [comment]
Only the finished job

Tim Neumann ***@***.***> schrieb am Mi., 21. Apr. 2021, 10:47:
