### ISSUE TITLE
mysql secondary init issue

### ISSUE THREAD

**Issue by jgillis01** [presslabs/mysql-operator#474]
When creating a mysql cluster with release version 0.3.8, it seems that the secondary init process cannot access port 8080 on the mysql-master service.  Checking that service, port 8080 is not being exposed.  This is causing the init container to fail since it cannot find an instance from which to clone data.  This seems to have been solved back in Jan with this commit: https://github.com/presslabs/mysql-operator/commit/58934f15b0fc7307213b3181944b1fef3c63ca57

Can we get a new release which includes this commit and addresses the init issue for the mysql secondary init process?

**Comment by AMecea** [comment]
Hi @jgillis01,

Nice catch, this wasn't a problem so far (I think on older k8s versions), what version of k8s do you use? I'm working on the next release 4.0 which has some breaking changes but it will take at least a week because some e2e tests are failing. I can do a quick release 3.9 with this fix if you want it sooner.

Thank you for reporting this issue!

**Comment by jgillis01** [comment]
Hi, @AMecea,

Thank you for the quick response!  We are currently running k8s version `v1.15.3.`  I can track `master` for now, but I am concerned about any breaking changes that coming down the line.  A new version would be much appreciated!

**Comment by jgillis01** [comment]
@AMecea,

After further investigation, it seems that the issue has to do with the `imagePullPolicy` on the operator statefulset.  It is set to `IfNotPresent.`  However, the images used are referencing the `latest` tag.  This is preventing the newest images from being pulled on subsequent deployments of the operator (The new master commits contain the changes to add port 8080 to the master service).  The pull policy is configurable in the helm chart values file so I think this issue is moot.  Thank you for your attention on this.
