### ISSUE TITLE
Unhealthy slave may be chosen as backup target

### ISSUE THREAD

**Issue by yoichiwo7** [presslabs/mysql-operator#475]
When backup runs on following conditions, incorrect master will be chosen as a backup target.

- All slaves are unhealthy
- Current master is non-zero StatefulSet pod (ex. mycluster-mysql-1, mycluster-mysql-2)

If the incorrect master is chosen, it means the unhealthy slave is going to be a backup target. This will lead to broken or useless backup files which will cause huge problems on recovery process.

## How to fix

Use `s.cluster.GetMasterHost() ` instead of `s.cluster.GetPodHostname(0)` to return the current running master node.

https://github.com/presslabs/mysql-operator/blob/32660f3ebd5266116622d8047a117a4408b53f95/pkg/controller/mysqlbackup/internal/syncer/job.go#L112-L114

**Comment by AMecea** [comment]
Hi @yoichiwo7, thank you for pointing that out, it's indeed a bug. I will love to review and merge a PR that does that :smile:
