### ISSUE TITLE
build the project error

### ISSUE THREAD

**Issue by Jacklli** [presslabs/mysql-operator#480]
[root@k8smaster mysql-operator]# make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/root/go/src/github.com/presslabs/mysql-operator/config/crds' 
RBAC manifests generated under '/root/go/src/github.com/presslabs/mysql-operator/config/rbac' 
cd hack && ./generate_chart_manifests.sh
./generate_chart_manifests.sh: line 8: yq: command not found
./generate_chart_manifests.sh: line 9: yq: command not found
./generate_chart_manifests.sh: line 10: yq: command not found
./generate_chart_manifests.sh: line 11: yq: command not found
./generate_chart_manifests.sh: line 12: yq: command not found
./generate_chart_manifests.sh: line 15: yq: command not found
./generate_chart_manifests.sh: line 25: yq: command not found
./generate_chart_manifests.sh: line 26: yq: command not found
./generate_chart_manifests.sh: line 27: yq: command not found
ginkgo --randomizeAllSpecs --randomizeSuites --failOnPending \
		--cover --coverprofile cover.out --trace --race --progress  \
		./pkg/... ./cmd/...
[1582176889] Sidecar App Suite - 4/4 specs •••• SUCCESS! 7.585136ms PASS
coverage: 30.6% of statements

i can not install yq command on centos, could you please help how to install this tool?

**Comment by AMecea** [comment]
Try to run `make dependencies-local`. This should fetch and install all the tooling that is needed in order to build the project.
