### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by abh** [presslabs/mysql-operator#490]
The mysql-operator is one of the highest maintenance operators I have in my cluster, because each update involves digging through git logs to have any sense of what might have changed.

It'd be really great to have release notes for each release, a CHANGES.md file or similar.

**Comment by AMecea** [comment]
I will do. I will create a `Changelog.md` file in the project's root directory. Sorry for that, we planned to use the GitHub releases as changelog but when I should fill that usually didn't have the time.

**Comment by AMecea** [comment]
this is addressed in #505

**Comment by abh** [comment]
awesome, thank you @AMecea!  It was great that you went back some releases, too!
