### ISSUE TITLE
error: unable to recognize "example-cluster.yaml": no matches for kind "MysqlCluster" in version "mysql.presslabs.org/v1alpha1"

### ISSUE THREAD

**Issue by egahmad** [presslabs/mysql-operator#491]
I'm getting this error following the basic tutorial with no extra customizations.

**Comment by danieltanyouzu** [comment]
Same issue reported on Ubuntu 18.04 on k8s 1.17.3 following the steps below.
https://www.presslabs.com/docs/mysql-operator/

**Comment by digitalcraft** [comment]
/any risk of someone replying to this in a reasonable timeframe?

**Comment by digitalcraft** [comment]
if you make a new branch, call it coronavirus. `rm -rf *`, then merge it into master, it should fix all the problems.

**Comment by AMecea** [comment]
Hi @egahmad and @digitalcraft. The CRDs are not installed. Please make sure that when you've installed the operator the CRDs get installed too.

Or install them manually by running:
```
kubectl apply -f https://raw.githubusercontent.com/presslabs/mysql-operator/master/config/crds/mysql_v1alpha1_mysqlcluster.yaml
kubectl apply -f https://raw.githubusercontent.com/presslabs/mysql-operator/master/config/crds/mysql_v1alpha1_mysqlbackup.yaml
```

May I ask how you've installed the operator?

**Comment by thordin9** [comment]
@egahmad @digitalcraft @AMecea i am having the same problem, i used helm 3 to install :

**manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"**
NAME: mysql-operator
LAST DEPLOYED: Sat Mar 21 23:03:22 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You can create a new cluster by issuing:

cat <<EOF | kubectl apply -f-
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 1
  secretName: my-cluster-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
type: Opaque
data:
  ROOT_PASSWORD: $(echo -n "not-so-secure" | base64)
EOF

it seems to have worked afterr applying the CRDs manually as you suggested. So i guess its a helm 3 related issue?

**Comment by xdimedrolx** [comment]
I have the same problem when using helm3

**Comment by umnya** [comment]
any updates for this? I have the same problem.

**Comment by Arabus** [comment]
You need to use the 0.4.0 release of the operator chart for this. otherwise the chart does not contain the crds directory. the templated CRDs get ignored by helm3 because of the unknown hook annotation

**Comment by Arabus** [comment]
Correction, the crds in the 0.4.0 version still contain the hooks and thus the CRDs are still ignored

**Comment by Arabus** [comment]
It appears this is intentional:
```
The crd-install hook has been removed and will not work for Helm v2 charts. A "legacy" plugin will be released by the Helm project to support v1 charts with the crd-install hook.
```
From https://helm.sh/blog/helm-v3-beta/#notable-changes-since-helm-v2

**Comment by AMecea** [comment]
Hi @Arabus, It's not clear to me what you are saying:

> Correction, the crds in the 0.4.0 version still contain the hooks and thus the CRDs are still ignored

[The hook](https://github.com/presslabs/mysql-operator/blob/f83d986f6f89c99fa31e33b0608a19bd0e730c7a/charts/mysql-operator/crds/mysql_v1alpha1_mysqlcluster.yaml#L9) is still there because we want to maintain backward compatibility with helm v2. But, version 0.4.0 works fine with helm3, the CRDs are installed, as far as I tested.

@thordin9 do you still get those errors even with version `v0.4.0`? 

Please let me know if there is any bug related to how CRDs are installed through helm.
Thank you for your contributions!

**Comment by Arabus** [comment]
Sorry for the confusion, installing the chart starting from v4.0.0 works fine with helmV3. I had the assumption that helmV3 ignored resources with unknown hooks but it appears it simply warns about ignoring the hooks.

It is unfortunate that one needs to specify an additional flag when running helm install --dry-run and helm template to actually see CRDs it would install (mssing those I thought the chart would not install the CRDs).

So everything is as it needs to be starting from v4.0.0 with helmV3
