### ISSUE TITLE
Slave I/O for Channel: mysql-operator-0.3.5

### ISSUE THREAD

**Issue by imriss** [presslabs/mysql-operator#499]
Getting these errors in one of the clusters. Mysql Operator is on version 0.3.5
```
2020-03-19T13:40:00.873285Z 12 [ERROR] Slave I/O for channel '': error connecting to master 'sys_replication@mysql-testns-mysql-0.mysql.testns' - retry-time: 10  retries: 8825, Error_code: 2005
```

The error was not there at the beginning of deploying of the cluster. The mysql pods always show 4/4. After deleting mysql-0, the error disappeared. 

Thanks

**Comment by munjalpatel** [comment]
@imriss I am also running into this. Did you ever resolve this?

**Comment by imriss** [comment]
@munjalpatel , at the time, the workaround was to delete (restart) mysql-0 pod. It could have been related to the timeouts (maybe the same for https://github.com/presslabs/mysql-operator/issues/406).
