### ISSUE TITLE
orchestrator.topologyUser=sys_operator results in 500 Internal Server Error: Unable to determine cluster name

### ISSUE THREAD

**Issue by radektheloner** [presslabs/mysql-operator#534]
Hello, please let my report you an issue that I have run into:

Reproducer:
1. Deploy the controller with `orchestrator.topologyUser` set to `sys_operator`
2. Deploy a cluster

Expected result:
The cluster is up and running

Actual result:
The cluster (the `mysql` container) reports following error:
> Access denied for user 'sys_operator'@'127.0.0.1' (using password: YES) 

The operator reports following warning:
> {"level":"warn","ts":1589272445.2589247,"logger":"controller.orchestrator","msg":"can't get instances from Orchestrator","msg":"not found","alias":"foo","stacktrace":...}

The orchestrator reports:
> Started GET /api/cluster/foo for 127.0.0.1:42168
> 2020-05-12 08:35:15 ERROR Unable to determine cluster name. clusterHint=foo
> [martini] Completed 500 Internal Server Error in 5.150245ms

Versions:
Controller 0.4.0-rc.1
Helm v3.1.2

Additional info:
- Setting `orchestrator.topologyUser` to something different (e.g. `orchestrator`) works around the issue.
- The value `sys_operator` was found in `charts/mysql-operator/README.md` where it is documented as the default value.
- The true default value is `orchestrator`.
- I started to suspect the `sys_operator` value to be the cause when I have noticed that the `/etc/mysql/conf.d/operator-init.sql` script in the `mysql` container looks like this:
```
...
DROP USER IF EXISTS sys_operator@'%';
CREATE USER sys_operator@'%' IDENTIFIED BY 'foo';
...
DROP USER IF EXISTS sys_operator@'%';
CREATE USER sys_operator@'%' IDENTIFIED BY 'bar';
...
```

I expect that either `sys_operator` does not cause an error or is not accepted as a valid input. I also expected that the default value documented in the mentioned README file matches the true default value and that the README file lets user know that `sys_operator` is not valid.

**Comment by AMecea** [comment]
Hi @radektheloner, thank you for pointing it out! I will correct the README.
