### ISSUE TITLE
Allow different Affinity / NodeSelector / Tolerations for backup jobs

### ISSUE THREAD

**Issue by rgershkovich** [presslabs/mysql-operator#540]
First of all, thank you for the hard work on the operator.

We encountered a situation I believe may not be unique to us. Some of the databases we run are very limited in compute resources. Unfortunately, with the current setup: https://github.com/presslabs/mysql-operator/blob/818452a2b1d4e8bb05521f71997d332bee1709fa/pkg/controller/mysqlbackup/internal/syncer/job.go#L141 backup pods are placed on the same nodes as MySQL itself without options to somehow distant them from mysqld. This results in poor performance on nodes that are resource-compromised, as xtrabackup is relatively CPU-intensive.

There are things we do to overcome this, using mutations on admission controller side, but it would be much easier if there were separate options in place for backup jobs.

Also, I think that would be useful in other use-cases, for example to speed up backups running them with higher thread count on separate nodes (https://github.com/presslabs/mysql-operator/pull/486).

Please let me know what you think about that, thank you!

**Comment by stankevich** [comment]
Thanks for the idea, @rgershkovich! https://github.com/presslabs/mysql-operator/pull/552 should take care of this. Let me know if that's what you had in mind.
