### ISSUE TITLE
unable to load the 

### ISSUE THREAD

**Issue by gouthamk10** [presslabs/mysql-operator#542]
Hello.
can somebody please help me installing mysl-operator.
i am getting this below error while installing mysql-operator from presslabs.

[root@k8s-master examples]# kubectl apply -f example-cluster.yaml
error: unable to recognize "example-cluster.yaml": no matches for kind "MysqlCluster" in version "mysql.presslabs.org/v1alpha1"

my yaml file defined in server.
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-secret

**Comment by olakunleoladimeji** [comment]
Perhaps you forgot to install the MysqlCluster CRD. In this case,

```
kubectl apply -f https://raw.githubusercontent.com/presslabs/mysql-operator/master/config/crds/mysql_v1alpha1_mysqlcluster.yaml
```

and re-install your YAML.

**Comment by gouthamk10** [comment]
Hi olakunleoladimeji.
Thanks for your help.i can install now.
