### ISSUE TITLE
sql_mode not the default for mysql

### ISSUE THREAD

**Issue by chasebolt** [presslabs/mysql-operator#543]
I ran into an issue with the operator setting a default `sql_mode` that contains `NO_AUTO_VALUE_ON_ZERO`. This mode is not a default for mysql 5.7 or 8.0. Is this intentionally set? If so we should document it in the readme or not set sql_mode so it falls back to the default of the mysql version deployed.

https://github.com/presslabs/mysql-operator/blob/d800e2483dcb018c15744782453101fced2c0a33/pkg/controller/mysqlcluster/internal/syncer/config_map.go#L171-L172

**Comment by calind** [comment]
The defaults were taken from https://github.com/presslabs/mysql-operator/issues/1. In retrospect, I think it's safe to remove the `NO_AUTO_VALUE_ON_ZERO`.

**Comment by Leen15** [comment]
Hi,
I think this issue is not resolved, maybe due to mysql 8 support that restored the sql-mode to the previous one:

https://github.com/presslabs/mysql-operator/blob/master/pkg/controller/mysqlcluster/internal/syncer/config_map.go#L239-L240
