### ISSUE TITLE
operator does not patch pod

### ISSUE THREAD

**Issue by D1abloRUS** [presslabs/mysql-operator#549]
Hello! After creating a cluster, the operator cannot patch under to hang new labels

kubernetes: 1.17.2

```
{"severity":"ERROR","timestamp":"2020-06-22T11:58:23.03836963Z","logger":"kubebuilder.controller","message":"Reconciler error","controller":"controller.mysqlcluster","request":"mautic/mautic","error":"Pod \"mautic-mysql-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n  core.PodSpec{\n  \t... // 20 identical fields\n  \tPriorityClassName: \"high-priority\",\n  \tPriority:          &100,\n- \tPreemptionPolicy:  nil,\n+ \tPreemptionPolicy:  &\"PreemptLowerPriority\",\n  \tDNSConfig:         nil,\n  \tReadinessGates:    nil,\n  \t... // 4 identical fields\n  }\n","stacktrace":"github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/presslabs/mysql-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/presslabs/mysql-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by AMecea** [comment]
Hi @D1abloRUS, I will take a look at it. It's possible that this is related to the old k8s client that we are using.

I will do a dependency update soon.

Thank you for your patience!

**Comment by olakunleoladimeji** [comment]
I would suggest deleting the underlying statefulset and let the operator recreate it. 

This shouldnt impact your PVC/data.

**Comment by jescarri** [comment]
Hey folks, any idea on how to fix this? Or does this bug limits the k8s versions this operator can be used?

thanks!

**Comment by AMecea** [comment]
Hi @jescarri, did you tried the operator on k8s version >= 1.17? Did you run into the same error as above?
I will run some tests on 1.17 too, now it's only tested on 1.16 and I will try to include support for 1.17 in release `0.5.0`

**Comment by pzduniak** [comment]
> I will run some tests on 1.17 too, now it's only tested on 1.16 and I will try to include support for 1.17 in release `0.5.0`

@AMecea Can you please explicitly mention what K8S versions are supposed to be supported in the README? We're just using the latest stuff and ran into this issue on 1.19. I can't even figure out if I'm doing anything incorrectly.

**Comment by jescarri** [comment]
@AMecea I tried it in 1.19 and got the error, I was thinking if readiness probes could do the job instead of patching the pod labels.

**Comment by vvkolesnikov** [comment]
@AMecea  Have any news? I used k8s 1.19 and 1.20 cluster and have this problem too.
