### ISSUE TITLE
Is this necessary to move from tmp to real name?

### ISSUE THREAD

**Issue by aisensiy** [presslabs/mysql-operator#567]
https://github.com/presslabs/mysql-operator/blob/28ef010d9c7e6acc2518b78ef44ae220040818f0/pkg/sidecar/apptakebackup.go#L85

It seems that the rclone upload itself will show if the clone is success or not, is this really necessary to rename the target name after make sure it is success? 

I found that some so called s3 compatible object storage service is not compatible enough to support `rename` api. So using `moveto` in rclone will make problems.

**Comment by AMecea** [comment]
Hi @aisensiy, This is a good safety guard for preventing us from ending up with corrupted backups. May I know what storage providers don't support `rename`?

**Comment by aisensiy** [comment]
Not so much providers have this problem... 😢  Unfortunately I am using [ucloud](https://ucloud.cn] which currently has this issue. I will contact with them and right now I will close this issue.
