### ISSUE TITLE
map is pointer, oldLabels and out.ObjectMeta.Labels always the same

### ISSUE THREAD

**Issue by jianhaiqing** [presslabs/mysql-operator#568]
https://github.com/presslabs/mysql-operator/blob/fc8e06df9009a361114ae417a089228ebb55a5d6/pkg/controller/mysqlcluster/internal/syncer/pod.go#L101

```golang
oldLabels := map[string]string{}

for k,v := range out.ObjectMeta.Labels {
	oldLabels[k] = v
}
```

I will open a PR later on.

**Comment by AMecea** [comment]
Fixed in: #576
