### ISSUE TITLE
The pod can't rejoin the mysql after failover happens.

### ISSUE THREAD

**Issue by jianhaiqing** [presslabs/mysql-operator#573]
https://github.com/presslabs/mysql-operator/blob/4d88be22e4b30c65c1a0fd60794533cbd4fe50e7/pkg/controller/orchestrator/orchestrator_controller.go#L231

If failover happened, and mysqlcluster stayed in failover-inprocess state. And orchestrator controller can't  be executed since there is no mysql cluster update.

So why not  add  timer to orchestrator controller, such as described below ?
```
return reconcile.Result{RequeueAfter: time.Duration(reconcileTime) * time.Second}, nil
```

**Comment by AMecea** [comment]
That's already what happens, see the https://github.com/presslabs/mysql-operator/issues/574#issuecomment-664467501. The cluster is enqueued each 5s.
