### ISSUE TITLE
Fresh MySQL slave comes up and scans all the bin logs on start-up

### ISSUE THREAD

**Issue by smedefind** [presslabs/mysql-operator#579]
We've started seeing an issue where we will build out a new replica from a master or another replica, and on mysql container start, a single threaded process reads all the log files. This takes upwards of 3 hours on our 220G database, and didn't happen months ago when we first built this cluster.

Nothing is stated in the MySQL logs, we had to attach strace to the process to see what it was doing.

We've had this happen in mysql-operator v0.4.0 and v0.4.0-rc1

Has anyone seen this?

**Comment by stankevich** [comment]
@smedefind: do you have [`binlog_gtid_simple_recovery`](https://dev.mysql.com/doc/refman/5.7/en/replication-options-gtids.html#sysvar_binlog_gtid_simple_recovery) disabled? Have a look at https://bugs.mysql.com/bug.php?id=69097 for more info.

**Comment by smedefind** [comment]
Thanks @stankevich , Turns out we've had General Logging enabled for months and it just takes forever for MySQL to scan the database on load.
