### ISSUE TITLE
Allow setting the cluster readOnly

### ISSUE THREAD

**Issue by calind** [presslabs/mysql-operator#58]
We should add a `spec.readOnly` which would set the entire cluster read-only (even the master node).

The controller should make sure that once the `readOnly` condition in status is set to `true`, there is no way the master becomes writable. It is ok to have a `spec.readOnly=false` cluster with all it's pod read-only, but it's a bug to have a `spec.readOnly=true` and `status.conditions[readOnly]=true` with writable pods.

For this we need to do the following:

1. [ ] all cluster pods start read-only
2. [ ] the controller is responsible of making the master pod writable
3. [ ] make sure that orchestrator is started with `ApplyMySQLPromotionAfterMasterFailover` set to `false`

**Comment by MerceaOtniel** [comment]
Addressed #100
