### ISSUE TITLE
Extra containers in server pods?

### ISSUE THREAD

**Issue by TonyBogdanov** [presslabs/mysql-operator#586]
I've noticed adding `podSpec.containers` has no effect on the generated statefulset.\
Is it at all possible to configure additional containers to run in the same pod along with the MySQL server?

My particular use case is that I use ProxySQL as a load balancer for a one-master-multiple-slaves topology, but my applications can't tolerate stale reads, thus I decided to give ProxySQL Binlog Reader a shot. For that I need an extra service running per server [as described here](https://www.percona.com/blog/2020/02/18/configuring-proxysql-binlog-reader/).

Alternatively I could also add the service to the percona image itself, albeit a nasty variant, but then I'd need to be able to specify my custom image somewhere in the manifests. Would _that_ be possible?

### Update

According to [this comment in the code](https://github.com/presslabs/mysql-operator/blob/master/pkg/internal/mysqlcluster/mysqlcluster.go#L210) it was intended to be possible to specify a custom MySQL server image via `spec.mysqlImage`, but a quick search shows it was never actually implemented. I'd love to help with that as I really need it at the moment. If only I knew Go...

### Correction

It seems it __was__ implemented, it's just called `spec.image`.

**Comment by TonyBogdanov** [comment]
@AMecea Fiddling with the base image will work nicely for my use case, so feel free to close this issue, unless of course, you like the idea of being able to customize containers and want to keep this as reminder.

**Comment by AMecea** [comment]
Hi @TonyBogdanov, thanks for using the operator!

Starting from version `v0.4.0` the operator has implemented: `MysqlCluster.spec.podSpec.containers` and should work. Did you use the latest version of the operator? Can you please confirm again that the containers are not getting updated on sts, maybe add here an example of cluster spec so I can reproduce it.

Thank you!

**Comment by elderapo** [comment]
@TonyBogdanov did you manage to add `ProxySQL` support by embedding it into `precona` docker image? If so would you mind sharing that dockerfile? :)
