### ISSUE TITLE
Unknown variable "binlog-space-limit" error when using mysql:5.7 image.

### ISSUE THREAD

**Issue by couch-potato08** [presslabs/mysql-operator#591]
Installed the cluster following [this](https://www.presslabs.com/docs/mysql-operator/deploy-mysql-cluster) docs. I am using the `mysql:5.7` image instead of the default `percona` MySQL image. I've also set volumeClaim in `volumeSpec` the cluster yaml, following [this](https://www.presslabs.com/docs/mysql-operator/deploy-mysql-cluster/#persistent-volume-claim). But using this combination of image & own volumeClaim results in the following error:

```
2020-08-24 21:15:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
2020-08-24 21:15:24+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
	command was: mysqld --verbose --help
	2020-08-24T21:15:24.711860Z 0 [ERROR] unknown variable 'binlog-space-limit=341M'
2020-08-24T21:15:24.717024Z 0 [ERROR] Aborting
```

I tracked the issue to the code here https://github.com/presslabs/mysql-operator/blob/288131ec062a1165c51562073b28443dbf59f26f/pkg/internal/mysqlcluster/defaults.go#L99

The variable "binlog-space-limit" does not exist for MySQL 5.7 config. Can this check on volumeClaim to set the variable "binlog-space-limit" be restricted to percona images only?

Operator version: 0.4.0

**Comment by AMecea** [comment]
Hi @couch-potato08, thanks for reporting this. I will add an extra check to don't set that config based on the image.
