### ISSUE TITLE
make image fails

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#60]
make image has dependency on cmd/gen-crds-yaml, and expects its directory and dockerfile under build directory.

`
CGO_ENABLED=0 \
        GOOS=linux \
        GOARCH=amd64 \
                go build -ldflags "-X github.com/presslabs/mysql-operator/pkg/util.AppGitState=dirty -X github.com/presslabs/mysql-operator/pkg/util.AppGitCommit=09e611034b4a166498414615f798a985ed3eb7d8 -X github.com/presslabs/mysql-operator/pkg/util.AppVersion=v0.1.4-dirty" \
                        -v -o bin/mysql-operator_linux_amd64 cmd/mysql-operator/main.go
CGO_ENABLED=0 \
        GOOS=linux \
        GOARCH=amd64 \
                go build -ldflags "-X github.com/presslabs/mysql-operator/pkg/util.AppGitState=dirty -X github.com/presslabs/mysql-operator/pkg/util.AppGitCommit=09e611034b4a166498414615f798a985ed3eb7d8 -X github.com/presslabs/mysql-operator/pkg/util.AppVersion=v0.1.4-dirty" \
                        -v -o bin/mysql-helper_linux_amd64 cmd/mysql-helper/main.go
CGO_ENABLED=0 \
        GOOS=linux \
        GOARCH=amd64 \
                go build -ldflags "-X github.com/presslabs/mysql-operator/pkg/util.AppGitState=dirty -X github.com/presslabs/mysql-operator/pkg/util.AppGitCommit=09e611034b4a166498414615f798a985ed3eb7d8 -X github.com/presslabs/mysql-operator/pkg/util.AppVersion=v0.1.4-dirty" \
                        -v -o bin/gen-crds-yaml_linux_amd64 cmd/gen-crds-yaml/main.go
set -e;
for cmd in mysql-operator mysql-helper gen-crds-yaml; do \
                        install -m 755 bin/${cmd}_linux_amd64 hack/docker/${cmd}/${cmd} ; \
                done
install: hack/docker/gen-crds-yaml/gen-crds-yaml: No such file or directory
make: *** [install-docker] Error 71
`

**Comment by AMecea** [comment]
Thank you @smanpathak
