### ISSUE TITLE
Curious to know about production readiness

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#62]
Hi,

This Operator seems interesting to us as it focuses on handling Percona. You mention in README that the operator is in alpha stage and that you are using it internally on non-critical workloads. I was wondering if you can elaborate on some of the essential missing pieces that would make it production ready.

Thanks!
Devdatta

**Comment by calind** [comment]
Hi,

For example the missing e2e tests(#55) or PodDisruptionBudget (#57) are some of our “internal” blockers. Also the scheduled backups are not quite ready yet (you need to manually give permissions for the service account doing backups).

Also there are no logical  backups yet (mysqldump) only physical ones (using xtrabackup).

For the moment I would recommend setting up a staging environment and deploy the operator there. Of course you can throw production traffic at it (as I said we do it) but do so if you have some experience administering MySQL and only if you understand the risks of these missing pieces.

**Comment by devdattakulkarni** [comment]
Hi @calind 

Thank you for the detailed reply.

**Comment by christianhuening** [comment]
are you using 0.2 in prod meanwhile?
