### ISSUE TITLE
How to recover backup locally

### ISSUE THREAD

**Issue by elderapo** [presslabs/mysql-operator#645]
What is the simplest way of recovering automatic backup locally (for dev/debugging purposes).

Let's say I have downloaded `mysql-cluster-auto-2021-01-04t12-00-00.xbackup.gz` and would like to recreate database ideally with a different name (instead of `my-db--production` I want `my-db--dev`).

Now I get a little bit stuck/confused as to what software I need and what steps need to be done. I am using `percona:5.7.26` both in prod (k8s cluster) and dev (docker-compose).

**Comment by AMecea** [comment]
Hi @elderapo, you can decompress the backup and run mysqld.

Using this command should prepare the files for the backup: 
```
cat mysql-cluster-auto-2021-01-04t12-00-00.xbackup.gz  | gzip -d |  xbstream --extract --directory=/var/lib/mysql
```

Or using docker:
```bash
mkdir data

# prepare mysql files
cat mysql-cluster-auto-2021-01-04t12-00-00.xbackup.gz | gzip -d |  docker run --rm -i -v $(pwd)/data:/data perconalab/percona-xtrabackup xbstream --extract --directory=/data

# run mysqld
docker run --rm -v <the path where backup was extracted>:/var/lib/mysql -p 3306:3306 percona:5.7
```

Hope this helps!
Best regads,

**Comment by elderapo** [comment]
That's exactly what I needed! Thanks!

Any idea if there is a simple way of renaming a freshly recovered database?

**Comment by elderapo** [comment]
This doesn't seem to work :( After restoring the database locally [this](https://gist.github.com/elderapo/f6879871c201172a2e29ee1cca086818) is what I get at startup. However, when I try recovering the same backup to the cluster (via `initBucketURL`) it works just fine.

I've used the same DB version in the cluster and locally (`percona:5.7.26`).

Any ideas?
