### ISSUE TITLE
mysql-operator-x pod always crash on mac k8s cluster create by talos

### ISSUE THREAD

**Issue by zvier** [presslabs/mysql-operator#656]
The k8s cluster is install with [talos](https://www.talos-systems.com/blog/easiest-kubernetes-on-a-mac/) on my mac. 
```go
kubectl get nodes
NAME                     STATUS   ROLES                  AGE   VERSION
talos-default-master-1   Ready    control-plane,master   39m   v1.20.1
talos-default-worker-1   Ready    <none>                 39m   v1.20.1
talos-default-worker-2   Ready    <none>                 39m   v1.20.1
talos-default-worker-3   Ready    <none>                 38m   v1.20.1
```

I install this mysql-operator according the README.md example. Everything seems to be going well, but mysql-operator-0 always crash. And I also try install postgres-operator successfully on the same k8s cluster.
```go
kubectl get pods
NAME                 READY   STATUS             RESTARTS   AGE
my-cluster-mysql-0   4/4     Running            0          5m6s
mysql-operator-0     1/2     CrashLoopBackOff   6          6m27s
```

Then, I look at the log about the orchestrator container in the mysql-operator-0 pod. The error messages is only this:
```
kubectl logs mysql-operator-0  orchestrator
2021-02-09 07:52:13 FATAL unable to open database file
```

So any one have ideas how to solve this problem ? Thanks ~

**Comment by zvier** [comment]
> The k8s cluster is install with [talos](https://www.talos-systems.com/blog/easiest-kubernetes-on-a-mac/) on my mac.
> 
> ```go
> kubectl get nodes
> NAME                     STATUS   ROLES                  AGE   VERSION
> talos-default-master-1   Ready    control-plane,master   39m   v1.20.1
> talos-default-worker-1   Ready    <none>                 39m   v1.20.1
> talos-default-worker-2   Ready    <none>                 39m   v1.20.1
> talos-default-worker-3   Ready    <none>                 38m   v1.20.1
> ```
> 
> I install this mysql-operator according the README.md example. Everything seems to be going well, but mysql-operator-0 always crash. And I also try install postgres-operator successfully on the same k8s cluster.
> 
> ```go
> kubectl get pods
> NAME                 READY   STATUS             RESTARTS   AGE
> my-cluster-mysql-0   4/4     Running            0          5m6s
> mysql-operator-0     1/2     CrashLoopBackOff   6          6m27s
> ```
> 
> Then, I look at the log about the orchestrator container in the mysql-operator-0 pod. The error messages is only this:
> 
> ```
> kubectl logs mysql-operator-0  orchestrator
> 2021-02-09 07:52:13 FATAL unable to open database file
> ```
> 
> So any one have ideas how to solve this problem ? Thanks ~

The problem the pv path. I will close this issue.

**Comment by apurwaj2** [comment]
@zvier  Could you elaborate more on how you fixed it? I did not understand the problem with pv path.
