### ISSUE TITLE
What does this line of code do

### ISSUE THREAD

**Issue by usernameisnull** [presslabs/mysql-operator#661]
in `mysql-operator/pkg/controller/mysqlcluster/mysqlcluster_controller.go`

```
 var _ reconcile.Reconciler = &ReconcileMysqlCluster{}
```
I don't understand

**Comment by AMecea** [comment]
Hi @usernameisnull, This line is there only to ensure that `struct ReconcileMysqlCluster` implements the `reconcile.Reconciler` interface.

**Comment by usernameisnull** [comment]
thank you,I get it
