### ISSUE TITLE
The program will panic when mysqluser is deleted

### ISSUE THREAD

**Issue by lizhongxuan** [presslabs/mysql-operator#687]
The program will panic when mysqluser is deleted.
macxuandeMacBook-Pro:.kube macxuan$ kubectl logs -f mysql-operator-0 -nmysql-operator operator
![image](https://user-images.githubusercontent.com/10513552/119309087-675efe00-bca0-11eb-8806-28e3df872e8b.png)

**Comment by zhongxuan123** [comment]
Using:  
kubernetes v1.19.4 
mysqlcluster 0.5.0-rc.2
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-693.el7.x86_64

**Comment by zhongxuan123** [comment]
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

**Comment by zhongxuan123** [comment]
PR: https://github.com/presslabs/mysql-operator/pull/688
