### ISSUE TITLE
Unreliable operation failing cluster creation

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#69]
I routinely observe this issue with the operator. If it is used for a few CRUD operations of mysql clusters, kept running for a while  and new cluster is created, the sync does not work properly. I am attaching logs from a pod in such state. If I delete the operator pod the fresh pod spun up by K8S syncs the state correctly right away.
I think the orchestrator reconciliation loop does not start, failing the pod labeling operation.
[op.log](https://github.com/presslabs/mysql-operator/files/2100173/op.log)

**Comment by AMecea** [comment]
I investigated this issue a little, and I found out that: when a cluster is deleted and recreated then it is not registered again into orchestrator reconciliation loop. I will fix it asap.

Is this your case @smanpathak ?

**Comment by smanpathak** [comment]
@AMecea yes, I found the cause and am sending out a fix for review.
