### ISSUE TITLE
Add operator documentation

### ISSUE THREAD

**Issue by AMecea** [presslabs/mysql-operator#92]
Create a docs section where to add a starting guide and more:
 * [x] How to setup a cluster and fine tuning (detail cluster secret data)
 * [x] Detail each cluster param
 * [x] How to connect to a cluster (created services)
 * [x] How set recurrent backups
 * [ ] How to migrate to from old cluster to mysql-operator

Also let's add here in comments what needs documentation, maybe I missed something.

**Comment by chenmin1992** [comment]
really need a document

**Comment by AMecea** [comment]
Hi @chenmin1992, I will add some doc asap, but until then you can check this [page](https://www.presslabs.com/code/mysqloperator/) for some basic documentation.

**Comment by chenmin1992** [comment]
thank you @AMecea, inform when the doc ready please.

**Comment by christianhuening** [comment]
would love some more docs too

**Comment by AMecea** [comment]
addressed by #215 and the documentation can be read at https://www.presslabs.com/code/mysqloperator/getting-started/
