### ISSUE TITLE
I want to run mysql-operator in ARM server

### ISSUE THREAD

**Issue by txbxxx** [presslabs/mysql-operator#934]
If I want to run this operator in ARM, do I need to make other configurations to the makefile, or can I just use Dockerfile directly

**Comment by drivebyer** [comment]
try https://github.com/ksmartdata/mysql-operator/pkgs/container/mysql-operator

**Comment by txbxxx** [comment]
> try https://github.com/ksmartdata/mysql-operator/pkgs/container/mysql-operator

Thank you, but I am using version 0.6.2. Are these versions compatible?
